### ISSUE TITLE
Wiki page with examples of usage

### ISSUE THREAD

**Issue by rpost** [ajoberstar/grgit#107]
"verba docent, exempla trahunt" ;)

**Comment by ajoberstar** [comment]
Not arguing that more docs wouldn't be helpful, but there are [examples in the Javadoc](http://ajoberstar.org/grgit/docs/groovydoc/index.html?org/ajoberstar/grgit/Grgit.html).

**Comment by ajoberstar** [comment]
See the new [doc site](http://ajoberstar.org/grgit).
