### ISSUE TITLE
Include conflicts in status

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#112]
StatusOp should return the conflicts (in case of merge issue).

**Comment by Blacktiger** [comment]
I just pulled down 1.7.0-rc1 and gave it a try locally. I'm not seeing any conflicts after running the merge though and it looks like the merge was aborted.


My test case creates a temporary git repo and changes the version property of gradle.properties inside that repo on two branches, then does a merge expecting a conflict. Here is the history I'm seeing when my test case completes. The final step is to merge master into develop, but as you can see the merge is incomplete and there are no conflicts.

```
/v/f/_/6/T/repository4611070629729257018folder (develop) $ git log --graph --oneline --decorate --all
* 5550b43 (HEAD -> develop) set version to 1.1.0-SNAPSHOT
| * 9b9decb (master) set version to 1.0.0
|/  
* 7eb8418 set version to 1.0.0-SNAPSHOT

/v/f/_/6/T/repository4611070629729257018folder (develop) $ git status
On branch develop
nothing to commit, working directory clean
```

**Comment by Blacktiger** [comment]
Oh, and I forgot to mention that I do see the new 'conflicts' section in the `grgit.status()` call but it's an empty array.

**Comment by Blacktiger** [comment]
Oh, nevermind I was catching all Exception types which was hiding a bug in my script, not a merge problem. Looks like it's working correctly now, thanks!

**Comment by ajoberstar** [comment]
Thanks for verifying. I'll get the final one out today or tomorrow.
