### ISSUE TITLE
grgit.clean() not work

### ISSUE THREAD

**Issue by huaxiaos** [ajoberstar/grgit#114]
Hi,
When I use the clean() method,it not work.My code is below:

def grgit = Grgit.open(
                    dir: file(path),
                    creds: new org.ajoberstar.grgit.Credentials(
                            BITBUCKET_USERNAME, BITBUCKET_PASSWORD))
            grgit.clean(directories: true)
            grgit.checkout(branch: branch)
            grgit.pull()

Hope for response,thanks

**Comment by ajoberstar** [comment]
Can you provide some more information? What specifically doesn't work? If it helps, the intended behavior is [verified in this test class](https://github.com/ajoberstar/grgit/blob/82d32d68a41bb96072ec78b5790e3e542b601bbc/src/test/groovy/org/ajoberstar/grgit/operation/CleanOpSpec.groovy).

**Comment by huaxiaos** [comment]
In my SourceTree client,this is the status before I use the clean() method
![image](https://cloud.githubusercontent.com/assets/8043228/15171191/f123f748-177e-11e6-9451-77b6aa156754.png)

When I use the method above,status is not change,it is not clean
![image](https://cloud.githubusercontent.com/assets/8043228/15171223/4767026c-177f-11e6-8af4-620aeee47318.png)

**Comment by huaxiaos** [comment]
I use the wrong way?Maybe should I use "reset()"?

**Comment by huaxiaos** [comment]
Sorry,is my fault
I should use the reset method,not the clean method

grgit.reset(commit: branch, mode: org.ajoberstar.grgit.operation.ResetOp.Mode.HARD)

successfully

**Comment by ajoberstar** [comment]
No problem. Glad you resolved it.
