### ISSUE TITLE
Uptake of AuthConfig.getSessionConfig()

### ISSUE THREAD

**Issue by dchesterman** [ajoberstar/grgit#118]
It looks like getSessionConfig was added to turn properties into jsch config, but there doesn't seem to be any uptake of the method yet.  When I set any properties with the associated prefix, they are not passed to the Jsch session.

**Comment by ajoberstar** [comment]
Can you provide some more information about what you tried? A few things that would be helpful:

- Which version of grgit?
- What were the specific arguments you passed?
- Any error messages?
- Anything you expected to have happen that didn't?
