### ISSUE TITLE
Support a force option on the checkout operation

### ISSUE THREAD

**Issue by itissid** [ajoberstar/grgit#119]
I was looking at the code in CheckoutOp to reconcile a detached HEAD. 
While on the detached HEAD, I first did a checkout: 
`grgit.checkout(branch: "test_branch", createBranch: true)`
and then tried to simulate the  `git checkout -B master test_branch` as documented [here](http://stackoverflow.com/questions/5772192/how-can-i-reconcile-detached-head-with-master-origin) with  `grgit.checkout(branch: master, startPoint: test_branch)`
But this [fails](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/CheckoutOp.groovy#L101) complaining on [this](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/CheckoutOp.groovy#L101) line. 
Using the orphan argument fails as well, I am actually not  sure why checkout was implemented that way, but it seems it can't do this operation.

**Comment by ajoberstar** [comment]
In general, there are two reasons grgit wouldn't give you the same options as CLI Git:

- It's based on JGit, which doesn't always have identical capabilities
- grgit was never intended to be comprehensive

In this case, [git-scm](https://git-scm.com/docs/git-checkout) indicates `-B` option is similar to using the `-f` (force) flag. There is a `force` option on JGit's [CheckoutCommand](http://download.eclipse.org/jgit/site/4.4.1.201607150455-r/apidocs/org/eclipse/jgit/api/CheckoutCommand.html), which I assume would provide what you need here.

I'll mark this as an enhancement, though not sure when I'd work on it. Certainly would accept a PR, if you (or anyone else) is interested.

**Comment by ajoberstar** [comment]
Actually, I just remembered the [grgit.branch.change()](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/BranchChangeOp.html) operation. This is probably why I skipped exposing the force option on checkout. All it buys you is doing two things at once, which isn't necessarily a good thing. I'm going to call this a won't fix.

**Comment by itissid** [comment]
Ah yes I used the combination of the `grgit.checkout` for creating a new branch and the `grgit.branch.change` to be able to make that track the remote. Thanks, this did solve my issue.
