### ISSUE TITLE
don't fail build during plugin application when no .git directory is available

### ISSUE THREAD

**Issue by lbergelson** [ajoberstar/grgit#120]
Currently, if there is no .git directory available it seems like grgit fails during plugin applications.

```
./gradlew compileJava

...

An exception occurred applying plugin request [id: 'org.ajoberstar.grgit', version: '1.5.1']
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > One of setGitDir or setWorkTree must be called.
```

This causes problems for distributing source separately from git.  Could this be changed to fail lazily only when commands are invoked rather than when the plugin is applied?  That way targets that don't rely on git could still run.

(sorry for the open/close/opening of the issue, I accidentally hit enter and created the issue with a nonsense title, so I closed it until I had time to finish typing it out.)

**Comment by ajoberstar** [comment]
Yes, that's a good idea. Could report this on [gradle-git](https://github.com/ajoberstar/gradle-git) which is where the Gradle plugin is implemented?

**Comment by lbergelson** [comment]
Sorry for posting in the wrong place!   I've moved the ticket.

**Comment by ajoberstar** [comment]
No problem
