### ISSUE TITLE
Authentication Using Personal access tokens to git

### ISSUE THREAD

**Issue by spencerbharath** [ajoberstar/grgit#121]
Is it Possible to authenticate Using Personal access tokens ?

**Comment by ajoberstar** [comment]
Yes. Personal access tokens are essentially treated as passwords, so just use it in place of your normal password and it should work fine.

**Comment by spencerbharath** [comment]
Thanks for the input @ajoberstar 
But when I give the personal auth token in the place of password the authentication process fails.

`gradle someTask -Dorg.ajoberstar.grgit.auth.username=XXXXusername -Dorg.ajoberstar.grgit.auth.password=XXXauthtoken -Dorg.ajoberstar.grgit.auth.force=hardcoded`

**Comment by ajoberstar** [comment]
I haven't had a chance to test this myself, so no other ideas yet.
