### ISSUE TITLE
ECDSA Key Issues

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#123]
[Some host key issues](https://github.com/ajoberstar/gradle-git/issues/145) may be related to ECDSA keys. JSch may have introduced support for this, so try upgrading to ensure we're on the latest and see if it resolves the issue.

Ideally, find some way to test this.

**Comment by jtbigwoo** [comment]
To test this issue, you can force a ECDSA key into the known_hosts cache for your user.  Then if you try connecting and ECDSA isn't supported the connect should fail.  The following steps worked for us when we were trying to work around this issue.

1. Edit ~/.ssh/known_hosts and remove the line that refers to your target server.
2. Run the following command to load a ECDSA key:
`ssh -o HostKeyAlgorithms=ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com <username>@<yoursite.com>`

It doesn't matter if you can actually log in, the key gets cached first and then the log-in is attempted.

Good luck!

**Comment by ajoberstar** [comment]
Thanks for the info

**Comment by phatblat** [comment]
In testing out this change in 1.8.0, I had to add the following system property to force Jsch to use the ECDSA host key instead of expecting an RSA key:

- `org.ajoberstar.grgit.auth.session.config.server_host_key=ecdsa-sha2-nistp256`

Is there a way to have Jsch work with either?
