### ISSUE TITLE
Grgit.clone not present?

### ISSUE THREAD

**Issue by jordansissel** [ajoberstar/grgit#125]
Howdy!

I have the following small build.gradle:

``` gradle
plugins {
  id 'org.ajoberstar.grgit' version '1.6.0-rc.1'
}

task foo << {
  grgit.clone(dir: "${buildDir}/logstash", uri: "https://github.com:/elastic/logstash.git")
}
```

Executing the foo task tells me the following:

```
Execution failed for task ':foo'.
> No signature of method: org.ajoberstar.grgit.Grgit.clone() is applicable for argument types: (java.util.LinkedHashMap) values: [[dir:/home/jls/projects/logstash-docs/build/logstash, uri:https:/
/github.com:/elastic/logstash.git]]
  Possible solutions: close(), open(), collect(), any(), find(), open(java.io.File)
```

I had a look at the grgit code and I see what looks like static method_missing handling for `clone`, but beyond that I'm not sure what to dig into. Several docs mention `Grgit.clone()` examples but I am not finding success.

I'm fairly new to gradle and groovy, so I might be missing something obvious here. Thoughts?

**Comment by ajoberstar** [comment]
The `grgit` object made available by the `org.ajoberstar.grgit` plugin is tied to the repo your Gradle build is in. For cloning a different repo, you want to make the static call `Grgit.clone()` (capital G). You will likely need to add the import as well.

**Comment by jordansissel** [comment]
Confirmed! I have my things working now. Thank you very much for the info :)
