### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by caphrim007** [ajoberstar/grgit#127]
Forgive me for this incredibly newbie question as I am very new to groovy in general, but is mvnrepository.com the preferred way of installing the grgit releases? or is some other method preferred?

thanks!

**Comment by ajoberstar** [comment]
Grgit is published to both JCenter and Maven Central. Using a dependency manager like those built in to Gradle or Maven are the easiest, but you can just download it from one of those places if you don't use a dependency manager.

The README has a link to the latest version on Bintray (JCenter).

**Comment by caphrim007** [comment]
Thanks a lot Andrew for the explanation!
