### ISSUE TITLE
complie question

### ISSUE THREAD

**Issue by cooltom1** [ajoberstar/grgit#130]
Hi, 
I download the sorce, then I compile the project, it produces the error message like this:
Error:(5, 0) Cause: repository not found: C:\temp1\grgit-1.7.0\grgit-1.7.0
<a href="openFile:C:\temp1\grgit-1.7.0\grgit-1.7.0\build.gradle">Open File</a>
when I click the Open File link, it points to the line of the gradle file:
plugin{
...
id 'org.ajoberstar.defaults' version '0.6.0-milestone.7'
...
}
how can I solve this problem?
thanks.

**Comment by ajoberstar** [comment]
This could be related to this bug #128. I'll have a look at it after I get the PR for that fixed. Probably will just need to bump up the version of the grgit plugin used in this build.

**Comment by ajoberstar** [comment]
Nope, this is actually a bug in the [gradle-defaults](https://github.com/ajoberstar/gradle-defaults). Your best workaround at this point is to clone the repo instead of doing a download. Not sure when I'll get to the defaults improvements.
