### ISSUE TITLE
grgit keeps asking passphrase for private key

### ISSUE THREAD

**Issue by TarasOsiris** [ajoberstar/grgit#131]
I am struggling to understand why grgit keeps asking for passphrase for my ssh key (it is already added via `ssh-add` and is displayed via `ssh-add -l`), can someone help to figure it out? 

After I enter password it works as expected, how can I get rid of the prompt?
<img width="680" alt="authentication_required" src="https://cloud.githubusercontent.com/assets/3141378/20797997/8e4d2388-b7dd-11e6-8528-dc989122c675.png">

**Comment by ajoberstar** [comment]
The best next step is to run with info level logging, which can provide more info about which options grgit thinks are available to it. If this is in a Gradle context add the `--info` flag. If it's some other program, you'll need slf4j to run at INFO level.
