### ISSUE TITLE
Request: describe can return a list of tags

### ISSUE THREAD

**Issue by linqcan** [ajoberstar/grgit#136]
Currently `describe `is only returning the most recent tag relative to HEAD commit:
```
$ git log -1 --pretty=format:%d
 (HEAD -> derpa, tag: BEPA, tag: APA, origin/master, origin/HEAD, master)
```

Request: `describe `should be able to return a list of all tags applied to HEAD.

**Comment by ajoberstar** [comment]
I'd refer you to the git describe docs for the CLI git. I don't think git describe is what you're looking for.

https://git-scm.com/docs/git-describe

With grgit, you could list all tags and find the ones that point to your head commit. It's just not a single command.

**Comment by linqcan** [comment]
You're right. An api method mirroring the real git describe should not have
this feature. I will look over your suggestion and come back if there are
issues.
Close #136.
