### ISSUE TITLE
Get latest commit from git subdirectory question

### ISSUE THREAD

**Issue by FrankS77** [ajoberstar/grgit#143]
Hello,

thanks for your plugin!
My reprository looks like this
- .git
- subdirectory1(jar) 
 |--  build.gradle
- subdirectory2(war)
 |--  build.gradle

The beginning of my gradle build files in the subdirs:
plugins {
  id 'org.ajoberstar.grgit' version '1.6.0'
}
ext {
    // Open the Git repository in the current directory.
    def git = org.ajoberstar.grgit.Grgit.open(file('..'))
    // Get commit id of HEAD.
    date= git.head().getDate()
}
println "date: " + date
...

The problem is that I get the date from last commit from the whole project
but I want the date of the last commit from the subdir like in the git command (here to get all commits only for subproject subdirectory1:
git log -- subdirectory1

Is that possible?

**Comment by FrankS77** [comment]
I solved it by myself:

import org.eclipse.jgit.revwalk.RevCommit;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.api.Git;
import java.text.SimpleDateFormat;

ext {
     // open local .git repository
     def grgit = org.ajoberstar.grgit.Grgit.open(file('..'))
     // current working branch fullname
     def branchName = grgit.branch.getCurrent().fullName
     println "project.name " + project.name
     
     
     Repository repo = grgit.repository.jgit.getRepository();
     Git git = new Git(repo);


     Iterable<RevCommit> commits = git.log().add(repo.resolve(branchName)).addPath(project.name).call();

     // need only latest commit from iterator
	  RevCommit commit = commits.iterator().next();
      System.out.println(new SimpleDateFormat("yyyy-MM-dd_HH-mm").format(new Date(commit.getCommitTime() * 1000L)));
 
      git.close();
}

**Comment by ajoberstar** [comment]
A couple notes on this.

. Once you apply `org.ajoberstar.grgit` you already have a `grgit` property on your project that's open to you're project's repository. No need for the `def grgit` line.
. You should be able to get this information more [directly from grgit](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/LogOp.html) without having to dive into JGit.

```groovy
def latestCommit = grgit.log(paths: [project.name], maxCommits: 1).find()
println new Date(time).format('yyyy-MM-dd_HH-mm')
```

**Comment by ajoberstar** [comment]
Feel free to reopen if this did not address your question.

**Comment by FrankS77** [comment]
Thanks! :-)
but your two lines don't work as aspected.  a "find()" don't give only the date as String
and "time" does not exists as a variable.
I rewrote the two lines to:

def latestCommitDate = grgit.log(maxCommits: 1).get(0).date
println latestCommitDate.format('yyyy-MM-dd_HH-mm')

This is much more simpler than my solution above!!
