### ISSUE TITLE
Feature Request : Expose jgit CloneCommand.setCloneAllBranches() method in Grgit CloneOp

### ISSUE THREAD

**Issue by dchesterman** [ajoberstar/grgit#145]
Was playing around in jgit with trying to clone _just_ the reachable master refs for large projects.

Request to expose this method in the Grgit CloneOp

```
	/**
	 * @param cloneAllBranches
	 *            true when all branches have to be fetched (indicates wildcard
	 *            in created fetch refspec), false otherwise.
	 * @return {@code this}
	 */
	public CloneCommand setCloneAllBranches(boolean cloneAllBranches) {
		this.cloneAllBranches = cloneAllBranches;
		return this;
	}
```

**Comment by ajoberstar** [comment]
Thanks for the feature request. I'm not sure when my next round of work on grgit will happen (or if this would be in it), but I'd certainly be willing to take a pull request.
