### ISSUE TITLE
Document replacements for deprecated api in Grgit

### ISSUE THREAD

**Issue by HeadOnAPlate** [ajoberstar/grgit#147]
In Grgit, the open methods where you pass in a rootDir and optional credentials are deprecated.
These refer to OpenOp as a replacement.
Yet in OpenOp the proposed way to open a connection to a repository refers back to the deprecated methods in Grgit.

Could this be clarified? Is there an actual alternative to the deprecated methods?

**Comment by ajoberstar** [comment]
The deprecated version of `open` is the one taking a single un-named argument. The documentation of [OpenOp](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/OpenOp.html) shows the new methods, which take named arguments depending on how exactly you want to search for the git directory.

**Comment by HeadOnAPlate** [comment]
I see. Clearly I need to improve my groovy understanding (and so should IntelliJ, as it keeps pointing me to the deprecated methods when clicking through any Grgit.open(dir:...) method calls defined in my gradle configuration).

Thanks for pointing that out :)

**Comment by ajoberstar** [comment]
No problem. I think the confusion is largely from the dynamic way the replacement methods were added. My plan is to make them more statically declared in 2.0.
