### ISSUE TITLE
Publish more recent release to plugins.gradle.org

### ISSUE THREAD

**Issue by eaaltonen** [ajoberstar/grgit#151]
As of 2017-03-22
https://plugins.gradle.org/plugin/org.ajoberstar.grgit

shows the latest available version as '1.6.0', which is behind
https://github.com/ajoberstar/grgit/releases

1.6.0 still has issue #128.

**Comment by ajoberstar** [comment]
The gradle plugin is in [gradle-git](https://github.com/ajoberstar/gradle-git.git) (for now, I plan to decouple all of the plugins in there over time), so that's a slightly different version number. I do need to publish one that includes this though, and will do so tonight.

**Comment by ajoberstar** [comment]
This is also tracked in ajoberstar/gradle-git#242.

**Comment by eaaltonen** [comment]
Not yet visible
https://plugins.gradle.org/search?term=ajoberstar+gradle-git

Does it really take so long to update, or is there something broken in the publishing mechanism?

**Comment by ajoberstar** [comment]
gradle-git's using an older mechanism to get into the portal and I think it got disconnected by some reorganizing. It'll take a while for me to see if I can sort that out. The plugin is in Jcenter though.

**Comment by ajoberstar** [comment]
Should be available in the portal now.
