### ISSUE TITLE
Exception when only username is provided

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#153]
GitHub auth token's can be passed as a username and no password, but currently taking a similar approach here using GRGIT_USER and no GRGIT_PASS will fail.

**Comment by marcphilipp** [comment]
We're also experiencing this issue in junit-team/junit5#782. Is there any workaround or a solution in sight?

**Comment by ajoberstar** [comment]
I think it will be a pretty easy fix, just haven't had time to look at it. May have some time tomorrow.

**Comment by ajoberstar** [comment]
Copying Marc's sample error to make this easier to find with search:

```
:documentation:asciidoctor
:prepareDocsForUploadToGhPages
:createCurrentDocsFolder SKIPPED
:gitPublishReset FAILED
:gitPublishClose FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gitPublishReset'.
> Ambiguous method overloading for method org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider#<init>.
  Cannot resolve which method to invoke for [class java.lang.String, null] due to overlapping prototypes between:
        [class java.lang.String, class java.lang.String]
        [class java.lang.String, class [C]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':gitPublishClose'.
> Could not get unknown property 'repo' for object of type org.ajoberstar.gradle.git.publish.GitPublishExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED
```

**Comment by ajoberstar** [comment]
1.9.1 is out now. I'll be making fix releases of a bunch of the other plugins to update their dependencies on this too.

**Comment by marcphilipp** [comment]
Thanks for the quick turnaround! The new version works now! 👍

**Comment by andrii-kovalenko-ct** [comment]
thanks for the fix: i hoped to have it!

Maybe now the migrating doc https://github.com/ajoberstar/gradle-git-publish#migrating-from-orgajoberstargithub-pages could be changed, e.g. at least refer credentials section to http://ajoberstar.org/grgit/docs/groovydoc/index.html?org/ajoberstar/grgit/auth/AuthConfig.html ?
