### ISSUE TITLE
Shallow clones?

### ISSUE THREAD

**Issue by thiagowfx** [ajoberstar/grgit#155]
Is there any way to do a `--depth 1` while cloning  a repository (=shallow clone)? I couldn't find such an option.

If there is no such an option indeed, please consider this a feature request. :)

**Comment by ajoberstar** [comment]
Currently this is not supported. It's also not in JGit (see [their feature request here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=475615)). Until that's resolved, it can't be implemented here either.

**Comment by ajoberstar** [comment]
Confirming that the JGit bug is still open as of 10/22/2017.

**Comment by anukriti-chawla** [comment]
Is shallow clone implemented in latest jgit 4.11 ?

**Comment by ajoberstar** [comment]
@anukriti-chawla Doesn't [seem to be](http://download.eclipse.org/jgit/site/4.11.0.201803080745-r/apidocs/index.html) implemented. The linked issue earlier in this thread is also still open.

**Comment by liza-mae** [comment]
Any update on whether this will be supported?

**Comment by AfzalivE** [comment]
Seems to be supported now.
https://download.eclipse.org/jgit/site/6.4.0.202211300538-r/apidocs/org/eclipse/jgit/api/CloneCommand.html
