### ISSUE TITLE
SSH auth with a specific user name

### ISSUE THREAD

**Issue by svairavan** [ajoberstar/grgit#159]
Hi,
Is there a property to config a username with an ssh key that doesn't user the default user name on the machine?  I tried setting the properties -Dorg.ajoberstar.grgit.auth.username=jenkins and that doesn't work.

**Comment by ajoberstar** [comment]
I don't believe SSH keys have a username. Are you just asking how to use an SSH not in the current user's `.ssh`? If so, there are options in the auth config to specify the full path to the key.

**Comment by svairavan** [comment]
SSH keys don't have a username but they need to be associated with a username to look up the ssh key on the server side.  I am using gerrit as an the code rep for git.  To push or pull from the repo it needs  to be something git clone ssh://<username>@gerrit.example.com:29418/<project>.  Is there a way to specify the username like that?  The work around I found is to hardcode the remote url and that works, but not everyone will be using the same username and ssh key.

**Comment by ajoberstar** [comment]
Ah, I think I'm following now. As far as I know, that's purely controlled by the URI and isn't influenced by anything else. I think you'll be stuck with something like this:

```groovy
def username = howeverYouCanFindThis()
def grgit = Grgit.clone(dir: 'whatever', uri: "ssh://${username}@gerrit.example.com")
```

**Comment by ajoberstar** [comment]
Please reopen if this is still an issue.
