### ISSUE TITLE
version 1.9.0 require Java8

### ISSUE THREAD

**Issue by nkiesel** [ajoberstar/grgit#160]
Release notes state that minimum Java version is Java 7, but seems the upgraded eclipse dependency require Java 8 because I get
`org/eclipse/jgit/api/Git : Unsupported major.minor version 52.0`

**Comment by ajoberstar** [comment]
Thanks for catching this, that's an unintended requirements change from my end. I'll note this in the release notes, but will probably release a patch the rolls that back. This kind of change should require a 2.0 on my side.
