### ISSUE TITLE
CheckoutConflictException

### ISSUE THREAD

**Issue by jdjamsa1** [ajoberstar/grgit#164]
I am having trouble just moving between branches, or between branches and a tag.  If I use the git command line to first checkout a tag and then checkout master, I can do that successfully.  But if I try to programmatically do the same with grgit, I get exceptions:

CheckoutConflictException: Checkout conflict with files 

There are likely to be differences in the contents of the files between the tag and master, but other than that I have made no local changes.  I have just two checkouts, one right after another.

Can you explain why that might occur, and how I can get around that problem?  

I have tried using jgit functionality to stash prior to the checkouts.  Same result.

**Comment by ajoberstar** [comment]
Sorry for the delayed response... You mention using JGit functionality to stash. Have you tried doing the two successive checkouts with JGit (and not Grgit)? I'd like to narrow down if it's grgit-specific or general to JGit.

**Comment by ajoberstar** [comment]
Please reopen if this is still an issue.
