### ISSUE TITLE
Getting the delta between two commits

### ISSUE THREAD

**Issue by Gongzt** [ajoberstar/grgit#167]
I tried writing some experimental code, but seems only able to find the file changes in each commit. So if I want to list all the changes from CommitA to CommitG, I have to go through each commit one by one and combine the delta into one full list.

Is there a way to compare two commits directly and list all the changes?

**Comment by ajoberstar** [comment]
Not in the current functionality. I'm pretty sure JGit has a diff command, but their API doc link seems to be broken on their site right now.

**Comment by ajoberstar** [comment]
For this feature are you looking for the same information provided by `grgit.show()`, but for a range of commits rather than a single one? That is, just listing the paths that changed not the contents of the files?

**Comment by Lucas3oo** [comment]
I am looking into add a grgit layer on top of JGit DiffCommand.
Is it OK to expose JGit classes in grgit API? Like in this case return a list of org.eclipse.jgit.diff.DiffEntry ?

**Comment by ajoberstar** [comment]
@Lucas3oo I generally haven't been exposing JGit classes in the Grgit API (unless you go down to it directly, i.e. `grgit.jgit`).

**Comment by Lucas3oo** [comment]
Yepp, then I will create a new class for DiffEntry so the GrGit API is consistent.

**Comment by Lucas3oo** [comment]
Hi
I am done with a fix for this. Check the pull request.
Tx
Lucas
