### ISSUE TITLE
Pull specific repository and refspec

### ISSUE THREAD

**Issue by eaaltonen** [ajoberstar/grgit#169]
I would need functionality similar to `git pull` from the command line:

- pull specific `repository`
- pull specific `refspec` (commit, branch or tag)

The obvious place to put them would seem to be [org.ajoberstar.grgit.operation.PullOp](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/PullOp.html).

I can try to come up with a pull request, but please comment on the idea.

**Comment by ajoberstar** [comment]
`PullOp` (which maps to JGit's [PullCommand](http://download.eclipse.org/jgit/site/4.7.0.201704051617-r/apidocs/org/eclipse/jgit/api/PullCommand.html)) already supports:

- `remote` (which maps to the JGIt `remote` supporting remote names or uris)
- `branch` (which maps to the JGit `remoteBranchName`)

From their doc, it doesn't imply much flexibility beyond the branch name. If you need full refspec support, you could separate it into a fetch and merge. [FetchOp](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/FetchOp.html) definitely supports refspecs.

**Comment by eaaltonen** [comment]
`remote` did indeed support also URIs.

I had some success using `fetch` + `merge` using a fixed `ref` of the form `refs/heads/<branch>`.
```groovy
grgit.fetch('refSpecs': [ref], 'remote': uri, 'tagMode': FetchOp.TagMode.AUTO)
grgit.merge('head': 'FETCH_HEAD', 'mode': MergeOp.Mode.ONLY_FF)
```

This allowed me to pull from a dynamically determined remote repository without risk of overwriting any configured `remote`s.

However, this approach failed when trying to pull a commit by **SHA**, which jgit apparently does not support yet.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=517858

I will have to use cgit for now, but for someone wanting to pull branches and tags I supposed the above would work.

**Comment by ajoberstar** [comment]
Thanks for the follow up. I've tagged this as one waiting on JGit.

**Comment by ajoberstar** [comment]
Confirming that the JGit bug is still open as of 10/22/2017.

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
