### ISSUE TITLE
Log op with topo order

### ISSUE THREAD

**Issue by Gongzt** [ajoberstar/grgit#173]
I am not sure what the ordering option is in used in log operation. However I would like to know how to use the topo ordering,  to avoid showing the commits from two parallel development track mixed together. Or is there another way to achieve this?

**Comment by ajoberstar** [comment]
Grgit uses the behavior JGit's [LogCommand](http://download.eclipse.org/jgit/site/4.7.1.201706071930-r/apidocs/org/eclipse/jgit/api/LogCommand.html). It doesn't appear to be documented, and they don't have a method to choose a different sort order currently.

If you're interested, I'd suggest submitting (or searching for) an issue with JGit for this enhancement.

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
