### ISSUE TITLE
Binaries in maven.org?

### ISSUE THREAD

**Issue by deyanstoykov** [ajoberstar/grgit#175]
The last version uploaded to the central maven repo is 1.8.0-rc.1 

I have noticed that this coincides with the change of git tag format from 'vX.X.X ' to 'X.X.X'. Is there an issue?

**Comment by ajoberstar** [comment]
I made some changes to the build process that included not publishing to Maven central anymore, but they are present in JCenter. The main reason is that Central is more of a hassle to publish to. Not ruling out starting up again, but it's not trivial.

**Comment by deyanstoykov** [comment]
Thanks, I got it form JCenter.
