### ISSUE TITLE
Can't import project to Eclipse if i use Grgit.open(currentDir: file('.'))

### ISSUE THREAD

**Issue by IkeaGithub** [ajoberstar/grgit#176]
My team is not able to import GIT repository which is having "Grgit.open(currentDir: file('.'))" line in the build.gradle. 

![image](https://user-images.githubusercontent.com/4608310/28163419-aa980538-67e8-11e7-8acc-bc1d7be5f05f.png)

**Comment by ajoberstar** [comment]
Where is the `.git` directory relative to your `build.gradle`?

**Comment by IkeaGithub** [comment]
@ajoberstar , Thanks for your comments on this. I have tried with "Grgit.open(currentDir: file('.'))" instead of "Grgit.open()" and it works fine....
