### ISSUE TITLE
Could not find org.ajoberstar:grgit.1.9.3 in android studio

### ISSUE THREAD

**Issue by saikiranVu** [ajoberstar/grgit#177]
I'm using Android studio 2.3.3,
I added dependency in my gradle file and it gives me below, not sure if i need to add any other plugins/dependencies for this to work?

my build.gradle dependencies looks like this:

> dependencies
 >{
>        classpath 'com.android.tools.build:gradle:1.5.0'
>        //classpath group: 'org.tmatesoft.svnkit', name: 'svnkit', version: '1.8.12'
 >       classpath 'com.github.dcendents:android-maven-plugin:1.2'
>        classpath 'org.ajoberstar:gradle-git:1.7.2'
>    }

I get this error below - 

Error:Could not find org.ajoberstar:grgit:1.9.3.
Searched in the following locations:
    file:/Applications/AndroidStudio.app/Contents/gradle/m2repository/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.pom
    file:/Applications/AndroidStudio.app/Contents/gradle/m2repository/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.jar
    https://repo1.maven.org/maven2/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.pom
    https://repo1.maven.org/maven2/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.jar
    https://nexus.com/service/local/repositories/snapshots/content/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.pom
    https://nexus.com/service/local/repositories/snapshots/content/org/ajoberstar/grgit/1.9.3/grgit-1.9.3.jar
Required by:
    :example-app:unspecified > org.ajoberstar:gradle-git:1.7.2

Did anyone encounter this issue?

**Comment by ajoberstar** [comment]
Hi, please take a look at #193 for details, but you should be able to get this from JCenter.

**Comment by saikiranVu** [comment]
Cannot find issue #193 ? can you comment me the link for #193. Thank you.

**Comment by ajoberstar** [comment]
Sorry about that, I meant #175.

**Comment by saikiranVu** [comment]
**I still get this error:**

Error:Could not find org.ajoberstar:gradle-git:1.9.3.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/org/ajoberstar/gradle-git/1.9.3/gradle-git-1.9.3.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/org/ajoberstar/gradle-git/1.9.3/gradle-git-1.9.3.jar
    https://jcenter.bintray.com/org/ajoberstar/gradle-git/1.9.3/gradle-git-1.9.3.pom
    https://jcenter.bintray.com/org/ajoberstar/gradle-git/1.9.3/gradle-git-1.9.3.jar
    https://repo1.maven.org/maven2/org/ajoberstar/gradle-git/1.9.3/gradle-git-1.9.3.pom
    https://repo1.maven.org/maven2/org/ajoberstar/gradle-git/1.9.3/gradle-git-1.9.3.jar
Required by:
    :app:unspecified

**My gradle file looks like this** 


buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            credentials {
                username MvnUser
                password MvnPwd
            }
            url 'https://xxxxxxxx
        maven{
            credentials {
                username GitUser
                password GitPwd
            }
            url 'https://github.com/ajoberstar/grgit.git'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath group: 'org.tmatesoft.svnkit', name: 'svnkit', version: '1.8.12'
        classpath 'org.ajoberstar:gradle-git:1.9.3'
        classpath 'com.github.dcendents:android-maven-plugin:1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

Can you possibly add wiki on how to add the dependency ? or point to something which will be helpful?

**Comment by PaoloneM** [comment]
This worked for me:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.ajoberstar:grgit:1.9.3'
    }
}
```

@saikiranVu I think you have to change `gradle-git` to `grgit` in package name.

**Comment by saikiranVu** [comment]
@PaoloneM Thank you, it worked 👍
