### ISSUE TITLE
Properly clean up JGit resources

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#182]
It appears that not all `Git` instances actually respect the `close` method. Instances created by `InitCommand` does not use the constructor that let's this happen. `CloneCommand` does appear to do this correctly, as does `Git.open`. If Grgit's `close()` called both the `Git.close()` and the `Repostory.close()` I think this would resolve the issue.

**Comment by ajoberstar** [comment]
Appears this may be a broader JDK (or at least JGit) issue:

- https://www.eclipse.org/forums/index.php/t/1078283/
- https://stackoverflow.com/questions/45266021/java-jgit-files-delete-fails-to-delete-a-file-but-file-delete-succeeds
- https://stackoverflow.com/questions/31606978/odd-behaviour-when-deleting-files-with-files-delete

**Comment by ajoberstar** [comment]
See the [resources](https://github.com/ajoberstar/grgit/tree/resources) branch for current attempts to fix.

**Comment by GFriedrich** [comment]
@ajoberstar I just stumbled into this problem and maybe found a reason here: When using the InitOp or CloneOp, you implemented it using the commands from JGit itself which in turn returns a JGit instance which will close the repository for you.
But in the [OpenOp on line 63](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/OpenOp.groovy#L63) you create the Git instance by calling the constructor. This will return a JGit instance which won't close the repository for you. Just adding "true" to the constructor parameters should do the job. Or is there a reason why you did not add this?

**Comment by ajoberstar** [comment]
I do remember seeing that when investigating this earlier, so I think that would be a good change. However, I remember also testing calling JGit's `Repository#close()` instead of the `Git#close()` to get around this kind of issue, but it didn't seem to do the trick. 

It's possible there are just multiple places that some file handles are leaking and I just need to catch them all. This is one place where Groovy is quite frustrating, because in Java I could very easily get some linting of all the Closeables that aren't getting closed.

**Comment by ajoberstar** [comment]
In trying to discover these pieces, I converted a bunch of the code to Java in https://github.com/ajoberstar/grgit/commit/07910c07df849e9e505897ffb37ab92e43faed93. Analyzing this Java code in SonarCloud, I found one resource not being closed, the `ObjectReader` that is opened when [`convertCommit`](https://github.com/ajoberstar/grgit/blob/b2c1fec826db19c1b05ca5665d5cc2624b2224ca/grgit-core/src/main/groovy/org/ajoberstar/grgit/util/JGitUtil.groovy#L105) runs. I'm going to try closing this and test out a git-publish build that has experienced some issues with unclosed resources.

**Comment by ajoberstar** [comment]
I think this is probably resolved, but now pretty sure this isn't the cause of git-publish's issue.
