### ISSUE TITLE
Why Tag#shortName is not available?

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [ajoberstar/grgit#194]
[Tag#fullName](https://github.com/ajoberstar/grgit/blob/db9fda7d57fd6bde7ceddaa3208e0b432c8d1191/src/main/groovy/org/ajoberstar/grgit/Tag.groovy#L43]

contains `refs/tags/` prefix, which is not useful in most of cases. Why tag's short name is not extracted?

Thanks.

**Comment by ajoberstar** [comment]
Have you tried `tag.name` instead of `tag.fullName`?

**Comment by andrii-kovalenko-ct** [comment]
damn, my bad, sorry - i saw only properties...
