### ISSUE TITLE
Push failure due to pre-receive hook declination does not generate error

### ISSUE THREAD

**Issue by capadon1131** [ajoberstar/grgit#197]
I'm using `grgit` to push updates to a repository from a Gradle task executed by a Jenkins job.

For one particular use case, I noticed that the Jenkins job was being marked as successful, but there was no corresponding commit noted in the target repository that should have received the changes.

After digging into things a bit, the push failed due to a pre-receive hook declination. From the `--debug` output:

```
13:28:27 13:28:27.654 [DEBUG] [org.eclipse.jgit.transport.PacketLineIn] git< unpack ok
13:28:27 13:28:27.654 [DEBUG] [org.eclipse.jgit.transport.PacketLineIn] git< ng refs/heads/develop pre-receive hook declined
13:28:27 13:28:27.655 [DEBUG] [org.eclipse.jgit.transport.PacketLineIn] git< 0000
```

The target repository had been configured to only allow modifications to the `develop` branch via a pull request. Adding an exemption for the automation account resolved the issue. 

That being said, I was surprised that an exception was not thrown in this case.

Is this a situation that `grgit` should have detected, or would this be considered an issue with the underlying `jgit` implementation that's being used?

Thanks

**Comment by ajoberstar** [comment]
Off the top of my head, it could be either, but I would expect more likely on grgit's side.

Ideally, if you could provide a PR with a test that can reproduce this, it could expedite a solution. Otherwise, I'll try to get to this whenever I make the next release.

**Comment by capadon1131** [comment]
Thanks for the quick reply. I'm hoping to have some time to look into this soon.

**Comment by ajoberstar** [comment]
If you find more information on this feel free to reopen.

**Comment by ajoberstar** [comment]
Duplicate of #216. Fixed now.
