### ISSUE TITLE
Please add examples of git clone in Gradle 4.3

### ISSUE THREAD

**Issue by vivekKodira** [ajoberstar/grgit#204]
Hi,
I'm new to Gradle. I've found this plugin referred to in several SO answers and in the [documentation](http://ajoberstar.org/grgit/grgit-clone.html) but have not come across a simple working example that I can run and see working. Most seem to be using older versions of Gradle. Would you please add documentation that uses an example gradle file using this plugin?

**Comment by ajoberstar** [comment]
Given the status of the project (see the readme), I have no plans to improve the documentation.
