### ISSUE TITLE
Support GITHUB_TOKEN environment variable

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#205]

**Comment by ajoberstar** [comment]
This is useful for GitHub actions.

**Comment by ansman** [comment]
This would be nice, but for now you can just use `x-access-token` as the username and `GITHUB_TOKEN` as the password.

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
