### ISSUE TITLE
Problem Cloning Repository

### ISSUE THREAD

**Issue by jorymullet** [ajoberstar/grgit#208]
Context:
- Windows 8
- Java 8
- Spring Boot
- Gradle
- IntelliJ is the IDE but the error also occurs from the command line

The program I am trying to launch has been done so successfully by my colleagues on their Apple laptops. I have followed the exact same steps as them in terms of the files they set up and settings they select and I still have yet to launch successfully.

-------------------------------------------------------------------------------------------

Problem:

Appears when I run `gradlew bootrun` (no `--stacktrace`):

```
11:29:25 AM: Executing external task 'bootRun -Dspring.profiles.active=local'...
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:clientInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clientInstall'.
> org.ajoberstar.grgit.exception.GrgitException: org.ajoberstar.grgit.exception.GrgitException: Problem cloning repository.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
3 actionable tasks: 1 executed, 2 up-to-date
Invalid remote: origin
11:29:41 AM: External task execution finished 'bootRun -Dspring.profiles.active=local'.
```

The full stack trace has several 'Caused by' lines that look like this:

`Caused by: org.ajoberstar.grgit.exception.GrgitException: org.ajoberstar.grgit.exception.GrgitException: org.ajoberstar.grgit.exception.GrgitException: Problem cloning repository.`

until the last 'Caused by' line which looks like:

`Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin`

The full stack trace can be seen here: [full_stacktrace.txt](https://github.com/ajoberstar/grgit/files/1482895/full_stacktrace.txt)

------------------------------------------------------------------------------------------

What I have tried:
- Crying
- Googling the error every way I can think for over a week now.

I can git clone and make pull requests at the repository I am working from just fine. I have authority to do these things, but when I run the program, it stumbles over the 

`Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin`

line which (in my research) sounds like it is an authorization issue. Also, I clone and pull, not from Git, but from Bitbucket. So, I am getting all the proper files and am able to send them back, but would I also need authority through Git in order to run the program?

Honestly, the error is vague enough that I don't even know for sure if it is struggling to clone the repo I think it is struggling with, I'm just guessing. Is there a way to know which repo it is unable to find the origin?

Any suggestion would be great, just know that I have looked through virtually every other issue on ajoberstar/grgit trying their suggestions without luck. I pray I am missing something super obvious.

Thanks ahead of time,

Joshua

**Comment by ajoberstar** [comment]
Can you provide your build.gradle (or any bits where you are using grgit)? To me that implies that your repo doesn't have an `origin` remote defined. But depending on your use case, the fix might differ.

**Comment by jorymullet** [comment]
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.4.3.RELEASE")
        classpath('com.craigburke.gradle:client-dependencies:1.3.1')
        classpath('com.google.code.gson:gson:2.8.2')
    }
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'com.craigburke.client-dependencies'

jar {
    baseName = 'automentor'
    version = '0.1.0'
}

repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
    }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

configurations {
    providedRuntime
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-data-rest")
    compile("org.springframework.boot:spring-boot-starter-data-jpa")
    compile("org.springframework.boot:spring-boot-starter-web")
    compile 'javax.json:javax.json-api:1.1'
    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.2'
    compile "org.glassfish:javax.json:1.1"
    compile "org.flywaydb:flyway-core:4.2.0"
    runtime("mysql:mysql-connector-java:6.0.3")
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    testCompile("org.springframework.boot:spring-boot-starter-test")
}


clientDependencies {
    installDir = 'src/main/resources/static/web/assets/vendor'
    npm {
        'jquery'('3.1.1')
        'mustache'('2.3.0')
    }
    bower {
        'jquery-ui'('1.12.1')
        'bootstrap'('3.3.7')
        'datatables.net-bs'('1.10.13')
        'datatables.net-scroller-bs'('1.4.2')
        'col-resizable'('1.6')
        'moment'('2.17.1')
    }
}

bootRun {
    systemProperties = System.properties
    addResources = true
    environment SPRING_PROFILES_ACTIVE: environment.SPRING_PROFILES_ACTIVE ?: "local"
}
```

Others working on this project have successfully run this program without this issue. However, they are all on mac machines. I have tested this program on 2 windows machines and both throw the same error leading us to believe it may be an incompatibility with windows and one of the packages. 

grgit is never explicitly called in the code but is called by an underlying package so I don't know what to show you to help in terms of actual code but if you have recommendations, I'm happy to comply.

**Comment by jorymullet** [comment]
`gradle bootrun --info` produces the following:

```
:clientInstall (Thread[Daemon worker,5,main]) started.
Loading dependency: moment@2.17.1
Loading dependency: jquery@3.1.1
Loading dependency: mustache@2.3.0
Loading dependency: jquery-ui@1.12.1
Loading dependency: bootstrap@3.3.7
Loading dependency: col-resizable@1.6
Loading dependency: datatables.net-scroller-bs@1.4.2
Loading dependency: datatables.net-bs@1.10.13

> Task :clientInstall
Putting task artifact state for task ':clientInstall' into context took 0.0 secs.
Executing task ':clientInstall' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.

Dependency not found in https://bower.herokuapp.com/packages/datatables.net-bs
Dependency not found in https://bower.herokuapp.com/packages/bootstrap
Dependency not found in https://bower.herokuapp.com/packages/datatables.net-scroller-bs
Dependency not found in https://bower.herokuapp.com/packages/moment
Dependency not found in https://bower.herokuapp.com/packages/col-resizable
Dependency not found in https://bower.herokuapp.com/packages/jquery-ui
The following authentication options are allowed (though they may not be available): [INTERACTIVE, HARDCODED, SSHAGENT, PAGEANT]
The following authentication options are allowed (though they may not be available): [INTERACTIVE, HARDCODED, SSHAGENT, PAGEANT]
using interactive credentials, if needed
The following authentication options are allowed (though they may not be available): [INTERACTIVE, HARDCODED, SSHAGENT, PAGEANT]
The following authentication options are allowed (though they may not be available): [INTERACTIVE, HARDCODED, SSHAGENT, PAGEANT]
using interactive credentials, if needed
The following authentication options are allowed (though they may not be available): [INTERACTIVE, HARDCODED, SSHAGENT, PAGEANT]
using interactive credentials, if needed
using interactive credentials, if needed
The following authentication options are allowed (though they may not be available): [INTERACTIVE, HARDCODED, SSHAGENT, PAGEANT]
using interactive credentials, if needed
using interactive credentials, if needed
:clientInstall (Thread[Daemon worker,5,main]) completed. Took 10.801 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clientInstall'.
> org.ajoberstar.grgit.exception.GrgitException: org.ajoberstar.grgit.exception.GrgitException: Problem cloning repository.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
3 actionable tasks: 2 executed, 1 up-to-date
```

**Comment by jorymullet** [comment]
I changed my client dependencies to the following:

```
clientDependencies {
    installDir = 'src/main/resources/static/web/assets/vendor'
    npm {
        'jquery'('3.1.1')
        'mustache'('2.3.0')
    }
    bower {
    }
}
```
At this point, the program ran, so that's where the problem seems to lie.

**Comment by ajoberstar** [comment]
Just noticed this is reported in craigburke/client-dependencies-gradle#91, so I'll close this out.

**Comment by jorymullet** [comment]
ajobestar, you are the man. Thanks so much for the help. That link was the exact solution.
