### ISSUE TITLE
Problem targeting path sets with reset and clean

### ISSUE THREAD

**Issue by GeoffPlumbee** [ajoberstar/grgit#209]
Hi, I've been trying to get the paths argument doing what I want for either reset or clean - if I specify an exact file that works fine, but if I specify a directory with untracked files under it - nothing happens.
Is this a limitation? or is there another way to recursively clean a directory that I am missing?

// this works fine
grgit.clean {
        paths = ['cleanme.txt']
}

// does not work
grgit.clean {
        directories = true
        paths = ['cleanme'] //(contains both tracked and untracked files)
}

**Comment by ajoberstar** [comment]
I don't have a test for this at the moment, but looking at [JGit's CleanCommand](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/api/CleanCommand.java#L148) there comments seem to imply that it should delete the directory reccursively. Not sure if it will matter but what if you end it with a slash?

**Comment by GeoffPlumbee** [comment]
thanks - I've tried various combinations of slashes, relative, absolute etc.. 
if the directory itself is untracked I can specify the directory and it will be deleted 
but if the specified directory is versioned then clean will not remove the untracked files below.
this is sounding like a problem with JGit?

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
