### ISSUE TITLE
Usage:How to count commits on master?

### ISSUE THREAD

**Issue by Johnlon** [ajoberstar/grgit#210]
We are using the git commit count in our artefact version.

We use ..  git rev-list --count HEAD
.. to get the count.

How can I achieve same using grgit?

Thanks

**Comment by ajoberstar** [comment]
You can leverage [log](http://ajoberstar.org/grgit/grgit-log.html) for this:

```
// if you want count from HEAD
grgit.log().size()

// if you want count from arbitrary starting point
grgit.log(includes: ['master']).size()
```

**Comment by Johnlon** [comment]
Do these perform well in long histories?

**Comment by ajoberstar** [comment]
I wouldn't expect it to perform as well as rev-list. It will parse commits along the way, but you'd have to try it to see if it's acceptable for your need.
