### ISSUE TITLE
How to delete/remove remote branches

### ISSUE THREAD

**Issue by jpork** [ajoberstar/grgit#214]
I would like to remove a remote branch. 
The first step is to remove it locally like so:

`grgit.branch.remove(names: ['myBranch'])`

But how do I push this delete operation to the remote?

**Comment by ajoberstar** [comment]
You'll need to use push (similar to the CLI):

```groovy
grgit.push(refsOrSpecs: [':refs/heads/mybranch'])
```

There's a few different syntaxes for the refspecs, you can see more info on this in [grgit-push](http://ajoberstar.org/grgit/grgit-push.html).

**Comment by Vampire** [comment]
@ajoberstar unfortunatley this does not work (anymore?)
> Caused by: org.ajoberstar.grgit.PushException: Failed to push: null to test_master

**Comment by Vampire** [comment]
Hm, it seems you need to fully-qualify the ref for it to work.
With `:refs/heads/test_master` instead of `:test_master` it works.
