### ISSUE TITLE
Allow the version of jgit used by grgit to be specified by the grgit client

### ISSUE THREAD

**Issue by donalhenry** [ajoberstar/grgit#215]
JGit has a number of bugs.  Having the grgit client specify the particular version of jgit to use, she would have more flexibility when these bugs are encountered.

**Comment by ajoberstar** [comment]
I don't know if there's a practical way to expose that. I think it would have to handle the JGit dependency resolution inside grgit to do so.

In a gradle context, you can modify the JGit dependency yourself to get around this (though it is cumbersome).

When using the plugin:

```groovy
buildscript {
  //....
  configurations.all {
    resolutionStrategy {
      eachDependency { details ->
        if (details.group == 'org.eclipse.jgit') {
          details.useVersion '<desired jgit version>'
        }
      }
    }
  }

  dependencies {
    classpath 'org.ajoberstar:grgit:<version>'
  }
}
```

When using as a library:

```groovy
//...
configurations.all {
  resolutionStrategy {
    eachDependency { details ->
      if (details.group == 'org.eclipse.jgit') {
        details.useVersion '<desired jgit version>'
      }
    }
  }
}

dependencies {
  compile 'org.ajoberstar:grgit:<version>'
}
```

**Comment by donalhenry** [comment]
Thanks.  Will try this.  Was also going to look at a section in "Idiomatic Gradle Plugins" (by Schalk Cronjé) to see if his approach could be used.
