### ISSUE TITLE
Push Fails Silently on Declined pre-receive Hook

### ISSUE THREAD

**Issue by mld-ger** [ajoberstar/grgit#216]
As stated in the title we encountered the issue that a pre-receive hook on our origin declined pushing tags and the plugin did not throw any exception which lead to inconsistent states in our versioning.
```
16:17:05.194 [DEBUG] [org.eclipse.jgit.transport.PacketLineIn] git< ng refs/tags/0.1.375 pre-receive hook declined
```

**Comment by ajoberstar** [comment]
2.2.0-rc.1 is out with a fix for this.

**Comment by p10shinde** [comment]
I am also facing the same error with JGIT 4.11(org.eclipse.jgit-4.11.0.201803080745-r) . In which release this is fixed? What version of JGIT jar do I need to take?

**Comment by ajoberstar** [comment]
Did you try grgit 2.2.0? The JGit version shouldn't affect this.
