### ISSUE TITLE
lsremote() fails to configure credentials

### ISSUE THREAD

**Issue by progig** [ajoberstar/grgit#222]
Hi,

When trying to use `grgit.lsremote()` a failure occurs:

Caused by: org.eclipse.jgit.errors.TransportException: https://myGitLabServer/myproject.git: Authentication is required but no CredentialsProvider has been registered.

I'm using Grgit version 2.1.1 with hardcoded credentials, `grgit.push()` and `grgit.pull()` just work fine.
Any idea why only `lsremote()` fails?

**Comment by ajoberstar** [comment]
Woops... Looks like I forgot to configure the Transport in [lsremote](https://github.com/ajoberstar/grgit/blob/ec77fb2df3cd7cbc39fb479eb14cf64ad14110e4/src/main/groovy/org/ajoberstar/grgit/operation/LsRemoteOp.groovy#L32) like I do in the other commands [push](https://github.com/ajoberstar/grgit/blob/ec77fb2df3cd7cbc39fb479eb14cf64ad14110e4/src/main/groovy/org/ajoberstar/grgit/operation/PushOp.groovy#L61). 

Definitely a bug and nothing on your end.

**Comment by progig** [comment]
Thanks for the quick response, good to hear it's a bug, I was already pulling my hair out. ;-). 
I'll wait for the fix!

**Comment by ajoberstar** [comment]
You can test the fix for this with 2.1.2-rc.1.

**Comment by progig** [comment]
Hi Andrew,

Tested with 2.2.0-beta.1, lsremote() works again.
Thanks a lot!

**Comment by ajoberstar** [comment]
Thanks for testing. I'm pushing out 2.1.2 final (which includes this fix). 2.2.0 needs some more work (for other features).
