### ISSUE TITLE
Grgit.open returns Null

### ISSUE THREAD

**Issue by mcgheebr** [ajoberstar/grgit#227]
My work recently decided to migrate from GitHub to TFS Git and since then when .open is called it returns null.  Per the docs it will return null if the .git directory does not exist but the directory is there and accessible.  Any ideas on what the problem is?  

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.ajoberstar:grgit:1.5.0'
    }
}

import org.ajoberstar.grgit.Grgit

ext {
    git = Grgit.open(currentDir: projectDir)
    gitVersionName = git.describe()
    gitReadableName = gitVersionName.split("-")[0]
    // Prior Devs manually incremented, hence the + 304 to keep up.
    gitVersionCode = git.tag.list().size() + 304
    gitVersionCodeTime = git.head().time
}

task printVersion() {
    println("Version Name: $gitVersionName")
    println("Version Readable: $gitReadableName")
    println("Version Code: $gitVersionCode")
    println("Version Code Time: $gitVersionCodeTime")
}
```

**Comment by ajoberstar** [comment]
Hmm, not sure what would cause that. Can you point to the doc that says a null will be returned in those situations? I'm not finding it.

Any reason you're still on 1.5.0? That's a 2 year old release, so it's possible a newer version wouldn't have that problem.

**Comment by mcgheebr** [comment]
Here is the URL to that documentation: [http://ajoberstar.org/grgit/grgit-gradle.html](http://ajoberstar.org/grgit/grgit-gradle.html)

I just tried the latest version and still received the same error: 
> Cannot invoke method split() on null object

**Comment by ajoberstar** [comment]
Ah. That document refers to use of the grgit plugin, which would result in the `grgit` property being null (along with a warning message) if it can't find a repo. You're using Grgit as a library by calling `Grgit.open()` directly. That method shouldnever return null.

With the error message you sent it looks like `git.describe()` is what returned null. That would imply that there are no tags reachable from your HEAD commit.

**Comment by mcgheebr** [comment]
You are correct, I did not pull down the tags and migrate them.  Everything works now and thank you very much :)

**Comment by ajoberstar** [comment]
Sounds good
