### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by sardar12** [ajoberstar/grgit#228]
Hi,
    Today when I was trying to download from git hub it was giving me the following errors

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>For /F "tokens=2-4 delims=/ " %a in ('date /t') do (set mydate=%c-%a-%b )

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>For /F "tokens=1-2 delims=/:" %a in ("10:35:37.24") do (set mytime=%a%b )

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>(set mytime=1035 )

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set JAVA_HOME=E:\MaximoDeployment\maximo\tools\java\jre

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set ANT_HOME=E:\MaximoDeployment\maximo\tools\ant

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set FINAL_lOG_LOCATION=\\max00\Data\ReleaseBuild\deployment-logs

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set TARGET_ENV=max70

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set DEPLOY_DIR=deployLogs

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set DEPLOY_FILE=_1035-MaximoDeployment-max70.log

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set MAXIMO_BUILD_DIR=\\max00\Data\ReleaseBuild\max-builds

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set ENV_BUILD_DIR=\\max00\Data\ReleaseBuild\env-builds

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>set PULL_LATEST=Y

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>rem ------------------------------------------------------------

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>For /F "tokens=2-4 delims=/ " %a in ('date /t') do (set mydate=%c-%a-%b )

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>For /F "tokens=1-2 delims=/:" %a in ("10:35:37.28") do (set mytime=%a%b )

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>(set mytime=1035 )

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>echo ------------------------------------------------------------
------------------------------------------------------------

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>echo Pulling Latest Code : Y : _1035
Pulling Latest Code : Y : _1035

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>echo   *** Assuments GIT Windows Auth Configuration  ***
  *** Assuments GIT Windows Auth Configuration  ***

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>echo ------------------------------------------------------------
------------------------------------------------------------

E:\repos\turbine_deployment\maximo_deployment\deploy-scripts>if "Y" == "Y" (git pull )
Fatal: HttpRequestException encountered.
Username for 'https://github.com':

**Comment by ajoberstar** [comment]
Hi, based on what you posted, it's not clear how (or if) you're using grgit. If you are, can you post more information about how you're calling it and how it's configured? Most people use it from Gradle, but otherwise it would be from Groovy.

**Comment by ajoberstar** [comment]
Feel free to reopen if you have more information.
