### ISSUE TITLE
Upgrade to JGit 5

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#233]

**Comment by childnode** [comment]
thanks, just to complete the linking:
* https://github.com/ajoberstar/grgit/commit/006b4a0ddbcd9d46b0de3c4f3bdf08d6885b158b
what has been mentioned in releaseNotes
> grgit.describe() now supports a tags option to include un-annotated tags (the default is false, but true would match the JGit 4 behavior)
