### ISSUE TITLE
grgit.clone() or grgit.push() for git lfs files

### ISSUE THREAD

**Issue by Ankush777** [ajoberstar/grgit#236]
I have configured gradle for building CI for my project and am extensively using Grgit. 
Appreciate the amazing work done there.
So, the issue i amfacing is that, initially i started CI builds with dummy repo which did not use [git-lfs](https://git-lfs.github.com/) but now when I am trying to move to the original repo am getting execption:
**Caused by: java.io.IOException: org.eclipse.jgit.api.errors.FilterFailedException: Execution of filter command 'git-lfs smudge -- '<name>.jar'' on file '<name>.jar' failed with return code '1', message on stderr: ''git-lfs' is not recognized as an internal or external command,
operable program or batch file.**

Line of code giving issue is coded as: 
**def grgit = Grgit.clone(dir: path, uri: '<http-reference>', credentials: new Credentials('username', 'password'))**

I need to know how can i clone/push to my repo where i have large files managed my git-lfs.

Env:
* Gradle 4.6
* Groovy 2.4.12
* JVM 1.8.0_144
* OS Win 7
* org.ajoberstar.grgit 2.1.0

Kindly provide me with your inputs. Little urgent.

**Attached StackTrace Logs**

[StacktraceLogs.txt](https://github.com/ajoberstar/grgit/files/2066207/StacktraceLogs.txt)

**Comment by Ankush777** [comment]
@ajoberstar 
Kindly have a look at this.

**Comment by ajoberstar** [comment]
It looks like JGit has an LFS module (see [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.eclipse.jgit)). I'm not familiar with that module though, so I don't know if it involves more than just including that dependency or if you have to do some other programmatic work to use it.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.

**Comment by Pytry** [comment]
Wondering if you've addressed this already? I'm having the same problem currently.
