### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by nilskp** [ajoberstar/grgit#239]
Not sure if I'm the only one, but our build is failing, with 404 trying to resolve the plugin.

https://plugins.gradle.org/m2/org/ajoberstar/grgit/org.ajoberstar.grgit.gradle.plugin/2.2.1/org.ajoberstar.grgit.gradle.plugin-2.2.1.jar

Redirects to JFrog's Artifactory, and the jar is not present. Any idea?

**Comment by nilskp** [comment]
Invalid. Some other issue going on.

**Comment by Shamil-kv** [comment]
The same error getting now
Could not find org.ajoberstar.grgit:grgit-core:4.1.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/ajoberstar/grgit/grgit-core/4.1.0/grgit-core-4.1.0.pom
       - https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.1.0/grgit-core-4.1.0.pom
       - https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/org/ajoberstar/grgit/grgit-core/4.1.0/grgit-core-4.1.0.pom
       - https://repo.maven.apache.org/maven2/org/ajoberstar/grgit/grgit-core/4.1.0/grgit-core-4.1.0.pom
     Required by:
         project : > com.gorylenko.gradle-git-properties:com.gorylenko.gradle-git-properties.gradle.plugin:2.2.4 > gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:2.2.4
