### ISSUE TITLE
Is focus really on "porcelain"?

### ISSUE THREAD

**Issue by Vampire** [ajoberstar/grgit#249]
`With the tooling focus, "porcelain" commands are the primary scope of what is included. Features that require more user interaction (such as resolving merge conflicts) are intentionally excluded.`

Is this really the intended wording?
It is a bit contradictory.
Tooling should use "plumbing" commands, humans should use "porcelain" commands.

**Comment by ajoberstar** [comment]
It's poor wording. It might be as simple as removing "With the tooling focus".

Maybe I have the wrong view on this, but I think the rationale for tooling using plumbing in C Git is mostly on the "meant for human consumption, not parsing" angle. In JGit, it's all APIs, so it's not meant for anything other than code/tooling. The angle of being subject to change may still apply, but it hasn't been a big issue in JGit so far.

**Comment by Vampire** [comment]
Ah, right, I see.
Not that I had another look at the GroovyDoc and what operations are there it makes sense.
It indeed are the porcelain commands you are providing.

I was probably really just confused to have "tooling" and "porcelain" in the same context when core Git says that for "tooling" you should use "plumbing". :-D
