### ISSUE TITLE
SSH support in 3.x

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#252]
3.0.0-beta.1 has made significant changes to SSH support.

- Removal of JSch support (i.e. an external `ssh` or `plink` command is required to either be on the `PATH` or pointed at via `GIT_SSH`)
- Removal of JSch agent proxy support (the external commands support the standard system agents or keychains)
- Removal of config for SSH session and specific SSH key to be used (as these were parts of JSch)

Please provide any feedback you have on this change. It's not a given that these will be removed in the final 3.0.

**Comment by ocroquette** [comment]
It would be nice to keep JSch around for users who don't want or cannot use an external program, and who can live with its limitations or issues.

**Comment by ajoberstar** [comment]
Just given my more limited bandwidth for this project, I'm going to move forward with the changes made in beta 1. That doesn't rule out adding back some of the options later, but I don't have the time to maintain them at the moment.

**Comment by ajoberstar** [comment]
Since this has been the behavior for a year, and I haven't received any further feedback, I'm closing this. This can be reopened or a new issue created if people have further feedback on the behavior.
