### ISSUE TITLE
Support for git describe abbrev length

### ISSUE THREAD

**Issue by martinmosegaard** [ajoberstar/grgit#254]
Since Git 2.11, the default abbreviation length is no longer always 7 digits. This means that the output of a plain `git describe` may vary. To get consistent behavior, we can use `git describe --abbrev=N`. But that does not seem to be supported by `grgit.describe`.

I am not familiar with jgit and whether this feature request should be reported there.

This issue seems related: https://github.com/ajoberstar/grgit/issues/238
and I am able to get a specific number of digits with the `getAbbreviatedId` function like: `grgit.head().getAbbreviatedId(7)`.

For background on the Git change, see:
- https://github.com/git/git/blob/aeddbfdfa48443c034a9b28b10dfddf2f71b907f/Documentation/RelNotes/2.11.0.txt
- https://public-inbox.org/git/87a7q3tze3.fsf@evledraar.gmail.com/T/

**Comment by ajoberstar** [comment]
It doesn't look like JGit's [DescribeCommand](http://download.eclipse.org/jgit/site/5.0.2.201807311906-r/apidocs/org/eclipse/jgit/api/DescribeCommand.html) supports specifying a fixed length for the abbreviated sha. If you happen to open an issue (or find one already open), please link it here so we can monitor the progress.

**Comment by martinmosegaard** [comment]
Thanks for the help with JGit. I have opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=537883 for JGit.

**Comment by 5deags** [comment]
https://download.eclipse.org/jgit/site/6.2.0.202206071550-r/apidocs/org/eclipse/jgit/api/DescribeCommand.html
Seems to be supported now

**Comment by sschuberth** [comment]
> Seems to be supported now

Thanks for reminding me, I had completely forgotten to comment back here after [I add this upstream](https://git.eclipse.org/r/c/jgit/jgit/+/189338) 😉

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
