### ISSUE TITLE
Docs on github have broken reference links

### ISSUE THREAD

**Issue by DALDEI** [ajoberstar/grgit#263]
The docs on the github site (this one) have many 404 links ...  Undfortunately they tend to be the linjks to documentation.  I havent yet learned enough to find  my way around easily so this is major barrier to trying out grgit

**Comment by ajoberstar** [comment]
Thanks for pointing this out. That link has been broken for a long time it seems. There's also a link to the reference docs in the header, which must be why this hadn't been reported before.

Did a quick scan and fixed the couple broken links I found. Please re-open if you find any more. Thanks again!
