### ISSUE TITLE
listing remote branches

### ISSUE THREAD

**Issue by jdjamsa1** [ajoberstar/grgit#265]
I don't understand why the results of calling grGit.branch.list(mode: BranchListOp.Mode.REMOTE) differs from the results of the git command 'git branch -r'.  The former returns two branches while the latter returns the number I expected, which is in the dozens.

I am using version 1.8.0-rc.1

**Comment by jdjamsa1** [comment]
actually, i have discovered that this unexplained behavior occurs when I am working with a project that is a clone of another git repository on the filesystem.   So the scenario is:  1) a git repo is cloned from github, and then 2) that local repo is cloned again.  it is this latter repo that exhibits the behavior described above (i.e. git branch -r works, but grGit.branch.list(mode: BranchListOp.Mode.REMOTE) does not)

**Comment by ajoberstar** [comment]
Unfortunately, I don't have any explanation for that. The listing mode is passed [directly to JGit](https://github.com/ajoberstar/grgit/blob/v1.8.0-rc.1/src/main/groovy/org/ajoberstar/grgit/operation/BranchListOp.groovy), so it could be some peculiarity of how it works.

**Comment by ajoberstar** [comment]
Not hearing other reports of this, going to close the issue. Can be reopened if others do see the same behavior and can provide more context/reproduction.
