### ISSUE TITLE
describe() works different from git describe

### ISSUE THREAD

**Issue by ThadHouse** [ajoberstar/grgit#270]
The issue located here

https://github.com/ajoberstar/gradle-git/issues/260

Still exists in grgit 3.0.

**Comment by ajoberstar** [comment]
If you're referring to which tags are included, see the new tags property on grgit.describe. I don't think JGit changed their default, but they added the option.

http://ajoberstar.org/grgit/grgit-describe.html

**Comment by ThadHouse** [comment]
That wasn't the issue I was seeing. I should probably file my issue upstream. The annotated part does now work correctly though.

The issue I am seeing is that if I have 2 tags pointing to the same commit, jgit returns the oldest tag, actual git returns the newest tag.

**Comment by ajoberstar** [comment]
Yeah, unless there's something we're not exposing from JGit, I'd file something upstream. If you do, feel free to open an issue about the specific behavior you want to see and provide a link to the JGit ticket.
