### ISSUE TITLE
Better rename tracking in ShowOp

### ISSUE THREAD

**Issue by mithomas** [ajoberstar/grgit#273]
Currently the `CommitDiff` returned by `ShowOp` does return a list of renames, which contains the new file name (as indicated by `renamed: entriesByType[ChangeType.RENAME].collect { it.newPath }`).

From my perspective it would be a good idea to either change `renamed` to a map from old to new filename or, to not break the API, to introduce a new field containing this information.

I'd be happy to provide a PR, if this is something accepted - what do you think?

**Comment by ajoberstar** [comment]
@mithomas Yes, this would be a nice change to the API. Let's keep it backwards compatible, and so add a new field, maybe `renamedOldToNew` or something similar. Would definitely welcome a PR! Sorry for the delayed reponse.

**Comment by ajoberstar** [comment]
Fixed by #281.
