### ISSUE TITLE
Failed to import classes in Gradle

### ISSUE THREAD

**Issue by diamondiona** [ajoberstar/grgit#280]
Hello,

I’m trying to load an external jar, grgit-core-3.0.0.jar, into my project. Always got “unable to resolve class org.ajoberstar.grgit.Branch” error.

Here is what I did:

download jar from https://jitpack.io/com/github/ajoberstar/grgit/grgit-core/3.0.0/grgit-core-3.0.0.jar

created a libs folder in root project directory(same level as build.gradle)

copy grgit-core-3.0.0.jar to “libs” folder

include this jar with following build.gradle

plugins {
id ‘groovy’
}

repositories {
mavenCentral()
}

dependencies {
implementation gradleApi()
implementation localGroovy()
//implementation files(‘libs/grgit-core-3.0.0.jar’)
//plugin fileTree(dir: ‘libs’, include: ‘.jar’)
implementation fileTree(dir: ‘libs’, include: [’.jar’])
}

sourceSets {
main {
groovy {
srcDirs = [‘buildSrc/src/main/groovy’]
}
}
}

I used “import org.ajoberstar.grgit.Branch” to import branch in Groovy code, got the following error:
C:\work\MessageBrokerGradlePlugin\buildSrc\src\main\groovy\ca\cooperators\mb\tasks\CloneGitRepoTask.groovy: 10: unable to resolve class org.ajoberstar.grgit.Branch
@ line 10, column 1.
import org.ajoberstar.grgit.Branch
^
1 error

:buildSrc:compileGroovy FAILED

I did a lot search to include external “.jar” file and tried many ways, none of them works.

Appreciate for help!

**Comment by ajoberstar** [comment]
Does `include: ['*.jar']` work in your `fileTree` call? 

Any reason you're not pulling it down as a Maven dependency? That's usually easier to deal with (because you're also going to need my transitive dependencies).

**Comment by diamondiona** [comment]
[MessageBrokerGradlePlugin.zip](https://github.com/ajoberstar/grgit/files/2961765/MessageBrokerGradlePlugin.zip)

I changed build.gradle according to this document: 
     http://ajoberstar.org/grgit/index.html

Here is the build.gradle: 

plugins {
	id 'groovy'
}

repositories {
	jcenter()

}




dependencies {
	implementation gradleApi()
	implementation localGroovy()
	//implementation files('libs/grgit-core-3.0.0.jar')	  
	//implementation fileTree(dir: 'libs', include: ['*.jar'])
	//implementation fileTree(dir: 'libs', include: ['*.jar'])
	//compile group:'org.ajoberstar.grgit', name : 'grgit-core', version : '3.0.0-beta.1'
	compile 'org.ajoberstar.grgit:grgit-core:3.0.0'
	
   
}


sourceSets {
	main {
		groovy {
			srcDirs = ['buildSrc/src/main/groovy']
		}
	}
}

Here is the error: 
C:\work\MessageBrokerGradlePlugin>gradlew build
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy
startup failed:
C:\work\MessageBrokerGradlePlugin\buildSrc\src\main\groovy\ca\cooperators\mb\tasks\CloneGitRepoTask.groovy: 10: unable to resolve class org.ajoberstar.grgit.Branch
 @ line 10, column 1.
   import org.ajoberstar.grgit.Branch
   ^

1 error

:buildSrc:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.463 secs

**Comment by diamondiona** [comment]
By the way, is there a way to tell we fileTree works properly? Thanks!

**Comment by diamondiona** [comment]
I did more tests, if I put groovy code under /src/main/groovy folder, everything works fine. But if I used customized src folder, such as: 
     sourceSets {
	main {
		groovy {
			srcDirs = ['buildSrc/src/main/groovy']
		}
	}
}

Then it won't work.
Task.groovy: 10: unable to resolve class org.ajoberstar.grgit.Branch
@ line 10, column 1.
import org.ajoberstar.grgit.Branch
