### ISSUE TITLE
How check if the local repository is up-to date or no ?

### ISSUE THREAD

**Issue by mlahmadix** [ajoberstar/grgit#285]
How check if the local repository is up-to date or no ?

I need to check if an update needed without launch the update (git pull).
Is there a way to know this (like git pull --dry-Run) ?

Thanks

**Comment by ajoberstar** [comment]
Either [lsremote](http://ajoberstar.org/grgit/grgit-lsremote.html) or [fetch](http://ajoberstar.org/grgit/grgit-fetch.html) would be the non-pull options.

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
