### ISSUE TITLE
Proper way to get branch name with Jenkins?

### ISSUE THREAD

**Issue by raphattack** [ajoberstar/grgit#286]
I have the following logic within my `build.gradle.kts` file:
`val prefix = if (git.branch.current().name == "master") "1" else "0.rc.$timestamp"`

This works great when I'm building locally, but when I build the `master` branch through Jenkins, `println(git.branch.current().name)` returns `HEAD` and thus the logic doesn't work.

What's the proper way to get the branch name when building with Jenkins?

**Comment by ajoberstar** [comment]
Your using the correct Grgit methods. From my recollection, Jenkins' default is that it doesn't checkout using the same branch name as the origin. You'll want to look into whether Jenkins has an option to change that.

**Comment by raphattack** [comment]
Thanks @ajoberstar.

Jenkins does indeed have the option to `Check out to specific local branch`.  Works perfectly if you set this option.
