### ISSUE TITLE
Is there NearestVersionLocator in grgit?

### ISSUE THREAD

**Issue by RIHELO** [ajoberstar/grgit#287]
Hi,
My project used NearestVersionLocator(gradle-git), but we are migrating to grgit 3.1.1.
Is there such class or way to get the nearest version?
Thanks

**Comment by ajoberstar** [comment]
Sorry for the delayed response. grgit does not include the `NearestVersionLocator`. If you need that functionality specifically, [nebula-release](https://github.com/nebula-plugins/nebula-release-plugin) took over the classes from the old gradle-git release plugin. If you just need the general idea, [reckon](https://github.com/ajoberstar/reckon) is my new plugin to address version inference. 

Let me know if you have further questions.

**Comment by ajoberstar** [comment]
Closing under the assumption this answered your question. If that's not true and you want to discuss further, please reopen.
