### ISSUE TITLE
Sync JCenter dependency with Maven Central

### ISSUE THREAD

**Issue by helpermethod** [ajoberstar/grgit#295]
Hi,

I'm developing a Maven plugin which uses grgit, which is great btw.

The problem is the dependency on JCenter :/. Doesn't JCenter allow syncing the with Maven Central? It would be so awesome if I could just request it from there.

Greets,
Oliver

**Comment by ajoberstar** [comment]
JCenter does support syncing, but you still have to support the requirements Central has. For now, I'm not going to spend any time getting those resolved.
