### ISSUE TITLE
Cannot open a parent directory with ".."

### ISSUE THREAD

**Issue by vmahuvak** [ajoberstar/grgit#296]
Grgit.open method is called in nebula-release-plugin when it reads from gradle.properties file a parameter 
git.root=..
It throws an exception. Any suggestion how to resolve this problem?

Thanks,

Vikram

**Comment by ajoberstar** [comment]
Sorry for the delayed response. Do you have some reproducible steps (or a small project) I could use to track this down?

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.

**Comment by vmahuvak** [comment]
Hi Andrew,
I worked with Google support and found that the CloudBuild trggers when starts to checkout your project_dir doesn't do full clone from git. SO it doesn't get .git directory in workspace where it builds my project in gradle. To avoid this issue of nebula-release trying to look for my last tagged version of the project. I set in gradle.properties file a property release.version= <major>.<miinor>.<patch> version that I want the tag to created.
Also on cloudbuild.yaml file had to be set in specific way to execute gradle command with build/final tasks.  I had to encrypt my git password in google by creating a symmetric key and than let Google cloudbuild decrypt it.
Google engineers will hopefully have a better solution for this in future.
Thanks for checking.
Vikram

    On Thursday, November 14, 2019, 5:58:57 PM PST, Andrew Oberstar <notifications@github.com> wrote:  
 
 
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
—your

**Comment by vmahuvak** [comment]
HI Andrew,
git.root = issue I resolved by giving full path. We had issue with git repo_dir whch was a leve hire than project_dir. The .git directory was at repo_dir level. I resolved this in git by moving all the files and directories to repo_dir level and deleting project_dir in git, This resolved the issue. I didn't have to set git.root anymore as project_dir and repo_dir were at same level.
Thanks for your help.
Vikram



    On Thursday, November 14, 2019, 8:19:19 PM PST, Vikram Mahuvakar <vmahuvak@yahoo.com> wrote:  
 
  Hi Andrew,
I worked with Google support and found that the CloudBuild trggers when starts to checkout your project_dir doesn't do full clone from git. SO it doesn't get .git directory in workspace where it builds my project in gradle. To avoid this issue of nebula-release trying to look for my last tagged version of the project. I set in gradle.properties file a property release.version= <major>.<miinor>.<patch> version that I want the tag to created.
Also on cloudbuild.yaml file had to be set in specific way to execute gradle command with build/final tasks.  I had to encrypt my git password in google by creating a symmetric key and than let Google cloudbuild decrypt it.
Google engineers will hopefully have a better solution for this in future.
Thanks for checking.
Vikram

    On Thursday, November 14, 2019, 5:58:57 PM PST, Andrew Oberstar <notifications@github.com> wrote:  
 
 
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
—your
