### ISSUE TITLE
grgit.branch.current().getName() returns HEAD instead of master/develop

### ISSUE THREAD

**Issue by Docjones** [ajoberstar/grgit#297]
Hi,

i am using grgit-gradle-plugin to retrieve the branch name for tagging my docker images during build using gitlab ci pipeline.

However, using `ext.branch = grgit.branch.current().getName()` to get the checked out branch name i receive `HEAD` instead of the expected `master`/`develop`.

Am i doing something wrong here?

thanks 
M

**Comment by ajoberstar** [comment]
It's possible that your CI is checking out a detached head rather than the named branch. I've seen that happen before in Jenkins. The might be a setting you can configure in the CI for this.

**Comment by Docjones** [comment]
Thanks for your help - we are using gitlab-ce. I haven't found any setting for this. Meanwhile, i am using a CI environment variable to detect the current branch. This works well for CI builds, but local ones will fail (since the CI environment is locally not available). The case can be closed. 
Thanks again for answering so swiftly :)

**Comment by makhaer** [comment]
I am also facing same problem. My build is in local and its failing with following message when trying to get the branch name
org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (String) values: [HEAD]
  Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()

**Comment by jeeftor** [comment]
I upgraded from version 3 something and now my call to:

```
def branch = grgit.branch.current().getName()
```

is returning: 

> Cannot get property 'branch' on null object

However if I drop the `.getName()` I have this:

> org.ajoberstar.grgit.Branch(refs/heads/feature/metrics, null, feature/metrics)

**Comment by glureau** [comment]
Update 2021 for those who have the same issue with **Jenkins**, you can add a `Behaviour` in "Branch Sources" named `Check out to matching local branch`.
![image](https://user-images.githubusercontent.com/7968075/121223725-1d713d00-c888-11eb-8611-3f8494c612f4.png)
