### ISSUE TITLE
Add CommitOp.sign field

### ISSUE THREAD

**Issue by tlinkowski** [ajoberstar/grgit#300]
Hi, first of all, thanks for a great library!

I'd like to be able to override signing for certain commits (it's due to #290 - I sign locally, but I want to disable signing from JGit).

This is possible in JGit's [`CommitCommand`](https://download.eclipse.org/jgit/site/5.4.0.201906121030-r/org.eclipse.jgit/apidocs/org/eclipse/jgit/api/CommitCommand.html#setSign-java.lang.Boolean-), but not in Grgit. I worked around it by [calling JGit directly](https://github.com/tlinkowski/tlinkowski-superpom/blob/67ed01e9718aa28370e95a46bf3b505f0fa92eca/subprojects/my-superpom-gradle-plugin/src/main/kotlin/pl/tlinkowski/gradle/my/superpom/shared/internal/GrgitExtensions.kt#L31-L59), but I think it'd be worth having this option in Grgit.

The following field would be needed in `CommitOp`:
```groovy
Boolean sign
```
and then in `CommitOp.call()`:
```
cmd.sign = sign
```

**Comment by ajoberstar** [comment]
Thanks for the suggestion! This would be a great issue for someone new to the library to contribute if they're (or you're) intested.
