### ISSUE TITLE
Supporting equivalent to "git clone --recurse-submodules"

### ISSUE THREAD

**Issue by freudi74** [ajoberstar/grgit#304]
I'm trying to clone/checkout a git repository using grgit, that has submodules.
Using git from commandline that can be done using:
`git clone --recurse-submodules`
There seem to be no way to do that with grgit, or am I missing something?
JGit seem to have a `setCloneSubmodules(boolean)` method in the CloneCommand class. Can support to use that be added to grgit?

**Comment by ajoberstar** [comment]
Yeah, if there's a JGit option it could be added. I'd welcome a PR for this, if you're interested.

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
