### ISSUE TITLE
Warn message when calling .close()

### ISSUE THREAD

**Issue by stefanleh** [ajoberstar/grgit#305]
When i use grgit in the following way i get a warn message:

    grgit.clone(dir: repo, uri: repoUrl, credentials: creds, refToCheckout: branch).withCloseable { 
        configGit -> 
                println "Konfigurationsrepository ${configurationRepositoryUrl} wurde nach ${repoPath} geklont."
    }

Message:

    close() called when useCnt is already zero for Repository[......./.git]

I expected: no warning as im using the AutoClosable functionality

**Comment by ajoberstar** [comment]
Which version of grgit are you using?

**Comment by stefanleh** [comment]
We use 4.0.0-rc.1 of the gradle plugin.

**Comment by stefanleh** [comment]
No change with 4.0.0.
I still get the warning.

**Comment by stefanleh** [comment]
Thanks.
