### ISSUE TITLE
Question about the release of 4.0.0

### ISSUE THREAD

**Issue by R1cc4rd07** [ajoberstar/grgit#306]
Hey there,
I am currently using the grgit version 3.1.1, in there I may found a bug related to an issue in jgit.
The release candidate 4.0.0 seems to fix my issue, because of the updated jgit dependence.
So my question is when do you plan to release 4.0.0?

sincerely Riccardo

**Comment by ajoberstar** [comment]
Thanks for the reminder. I forgot I had a rc sitting out here. I'll get it released tonight.

**Comment by R1cc4rd07** [comment]
Thank you.
