### ISSUE TITLE
Can't push to gitLab

### ISSUE THREAD

**Issue by sferrazjr** [ajoberstar/grgit#308]
Hi,

I have a Multibranch Pipeline in Jenkins that I configured using a regular Jenkinsfile. The project is using GIT_SSH as the snippet shows bellow

`Fetching origin...
Fetching upstream changes from origin
 > git --version # timeout=10
 > git config --get remote.origin.url # timeout=10
using GIT_SSH to set credentials jenkins user
 > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* # timeout=10`

The Jenkinsfile calls a couple of gradlew scripts and one of then if for handling new tags:

`sh "./gradlew tagMyProject"`

I that script I can get a list of tags using grgit.tag.list() without problem.

then I create a new tag without problem
`grgit.tag.add {
            name = "new_tag"
            message = "Automatic tagged"
        }
` 

but when the script calls 
`grgit.push {
            tags = true
}`
I get the message 
`> org.eclipse.jgit.api.errors.TransportException: git@myproject.git: > GitLab: The project you were looking for could not be found.`

From the documentation I understood that it won't be necessary to pass the credentials when opening the repo

**Comment by ajoberstar** [comment]
Where is the push initiated from? This not found message makes it look like your origin doesn't line up with actual Gitlab URL. But hard to say for sure. I've never used GitLab, maybe they use that error message for permission errors too.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
