### ISSUE TITLE
Getting the name of the branch a PR is originated from

### ISSUE THREAD

**Issue by rkrisztian** [ajoberstar/grgit#311]
With GrGit, I need to do similarly to #40, but with `origin/HEAD` as the parameter, instead of `HEAD`:

```bash
git rev-parse --abbrev-ref origin/HEAD
```

Is it possible to do that in GrGit? I couldn't find a trivial way.

Reasoning: I have a pull request hosted in Bitbucket, checked out by GoCD, and in the pull request checkout I need to find the name of the branch the PR is originated from, i.e. not the name of the PR branch.

Example command outputs:

```
$ git rev-parse --abbrev-ref HEAD
my-project-name/3
$ git rev-parse --abbrev-ref origin/HEAD
origin/master
```

As you can see, the first command outputs the path to the PR as a branch name, where 3 is the ID of the PR. And the second form works because of some GoCD magic I could not identify yet.

**Comment by ajoberstar** [comment]
Assuming the currently checked out branch tracks the remote branch, you can probably do this:

```
grgit.branch.trackingBranch.current.name
```

**Comment by rkrisztian** [comment]
Thanks, sadly it doesn't:

```
No such property: trackingBranch for class: org.ajoberstar.grgit.service.BranchService
```

**Comment by ajoberstar** [comment]
Sorry, ordered it wrong.

```
grgit.branch.current.trackingBranch.name
```

**Comment by rkrisztian** [comment]
No problem. Now I got:

```
Cannot get property 'name' on null object
```

**Comment by ajoberstar** [comment]
I think that would indicate that GoCD isn't checking out the repo to a branch that tracks a remote branch.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
