### ISSUE TITLE
Permission denied when applying plugin

### ISSUE THREAD

**Issue by harpritt** [ajoberstar/grgit#313]
Hi, I/We were just wondering if when applying the grgit plugin an attempt is made to modify .gitconfig. I ask because recently our build team locked down .giconfig to prevent it being modified which in turn lead to :

`A problem occurred evaluating root project 'xyz'.
> Failed to apply plugin [id 'org.ajoberstar.grgit']
   > /home/jenkins/.gitconfig (Permission denied)`

Kind Regards

Harpritt

**Comment by ajoberstar** [comment]
I don't believe it should be doing that. Do you have a stacktrace you can provide?

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
