### ISSUE TITLE
Getting "missing commit" error with GitHub Actions

### ISSUE THREAD

**Issue by riclage** [ajoberstar/grgit#316]
In our project we have a gradle file with the following:

```
    git = org.ajoberstar.grgit.Grgit.open(currentDir: projectDir)
    gitVersionName = git.describe()
```

On a github actions build, the `git.describe()` call is failing with the following error:

>  A problem occurred evaluating script.
> Missing commit: [commit SHA]

The commit SHA reported is the one right before the first one in the PR. It seems `git.describe()` does not see the commits inside the PR.

The above code works on a Travis build though. Any idea on what could be causing this?

**Comment by ajoberstar** [comment]
If you're using the v2 checkout action it defaults to a fetch depth of 1. I wonder if that's what's causing your problem.

**Comment by riclage** [comment]
How could I check?

**Comment by riclage** [comment]
It is indeed that. I replaced the action with `actions/checkout@v1` and everything works. Any idea what is causing this and how to fix it?

**Comment by ajoberstar** [comment]
They have details in the readme of the checkout action with more info. I think that will cover anything you would need to do to fix it.

https://github.com/actions/checkout/blob/master/README.md

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
