### ISSUE TITLE
No repository found

### ISSUE THREAD

**Issue by BullseyeSmith** [ajoberstar/grgit#317]
@ajoberstar, I see you're currently online posting things & I have a Q about the grgit plugin you wrote.  Forgive me for not knowing how to chat directly on github or if I'm posting this in the wrong area, I'm pretty new at all of this, including java.
BACKGROUND: I'm trying to make a plugin for MekHQ. I DL the latest build files (mekhq-0.47.5) and tried to run the included gradlew.bat right away to confirm it builds clean before I start messing with stuff. It doesn't. I get the same error message whether I use gradelw.bat directly (I'm on W10), or if I use the command line 'gradle gradlew', or if I run the clean & build option from within Netbeans.

ERROR: The error reads as follows...
> Configure project :
No git repository found for :. Accessing grgit will cause an NPE.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\me\Downloads\mekhq-0.47.5\mekhq-0.47.5\build.gradle' line: 32

* What went wrong:
A problem occurred evaluating root project 'MekHQRoot'.
> Cannot get property 'branch' on null object

CODE: Within the build.gradle file, line 32 states...
    hqBranch = grgit.branch.current().name

This is everything leading up to line 32:
plugins {
    id 'org.ajoberstar.grgit' version '2.3.0'
}

allprojects {
    apply plugin: 'java'
    
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    
    repositories {
        mavenLocal()
        maven {
            url 'https://github.com/MegaMek/mavenrepo/raw/master'
        }
        jcenter()
    }
}

subprojects {
    group = 'org.megamek'
    version = '0.47.5'
}

ext {
    hqGitRoot = 'https://github.com/MegaMek/mekhq.git'
    mmGitRoot = 'https://github.com/MegaMek/megamek.git'
    mmlGitRoot = 'https://github.com/MegaMek/megameklab.git'
    // Work on MML or MHQ sometimes requires changes in MM as well. The maven publishing tasks use
    // these properties to append the branch name to the artifact id if the repo is not in the master
    // branch, making it available separately to the child project. 
    hqBranch = grgit.branch.current().name

I understand it can't get 'branch' property on the grgit object because accessing grgit caused an NPE. I'm guessing the problem is because the expected org.ajoberstar.grgit (version '2.3.0') plugin listed on line 2 isn't part of the build package, nor did it pull it from the web.

QUESTION 1: Does grgit need to be defined somewhere in this build file, or will the grgit object be defined once the plugin is properly available?
QUESTION 2: How do I install org.ajoberstar.grgit plugin for gradle, or how do I correct the build.gradle file to correctly access the git repository?

Thanks in advance for your forthcoming wisdom. :)

**Comment by ajoberstar** [comment]
Did you clone the repo or download as a zip? That message usually indicates that you aren't in a git repo.

**Comment by BullseyeSmith** [comment]
I downloaded the build as a zip & extracted all.  I installed gradle.  I am not familiar with the term "clone the repo".

**Comment by BullseyeSmith** [comment]
I chose the "Source code (zip)" option of listed assets for the v0.47.5 Development Snapshot

**Comment by BullseyeSmith** [comment]
I'll research how to clone the git repository and give that a try.  If you have any other tips, I'm all ears.  I'm willing to mark this as closed if you think that's my only problem.
