### ISSUE TITLE
grgit.describe with longDescr = false always returns long description

### ISSUE THREAD

**Issue by yogurtearl** [ajoberstar/grgit#321]
Version 4.0.2

`longDescr = false` option appears to have no effect.
http://ajoberstar.org/grgit/grgit-describe.html

```groovy
grgit.describe {
    longDescr = false
}
```
(`longDescr = false` is also the default)
When the tag is `1.2`

**Actual**
returns `1.2-14-ad153dcf`

** Expected **
returns `1.2`

**Comment by mcanalesmayo** [comment]
Running into this issue as well, this is not working as expected

**Comment by ajoberstar** [comment]
Are you running `grgit.describe()` when you're directly on the tag?

My understanding of the behavior is this.

Commit history:

```
abc1234 (tag: 1.2)  My Commit 1
def5678 My Commit 2
```

If you have `def5678` checked out:

```
grgit.describe() == '1.2-def5678`
```

If you have `abc1234` checked out:

```
grgit.describe() == '1.2'
grgit.describe(longDescr: true) == '1.2-abc1234`
```
You can also look at [the tests](https://github.com/ajoberstar/grgit/blob/main/grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/DescribeOpSpec.groovy) to see the scenarios being validated.

If you still think this isn't  behavior right, can you send in a PR with a test showing what you believe it should be doing. I think we're in line with JGit behavior here, but I could be missing something.

**Comment by luizfp** [comment]
For me it would also be nice to have a way to get only the tag name, without the commit.
