### ISSUE TITLE
SSH authentication with HTTPS remote fails inexplicably

### ISSUE THREAD

**Issue by idontusenumbers** [ajoberstar/grgit#323]
I have a cloned bitbucket repo that uses SSH authentication. Git has the remote stored as `https://charlie_hayes@bitbucket.org/charlie_hayes/turbokiva.git`. When I do `git push` from terminal, it pushes just fine. When I do `gradle final` to trigger nebula release, it tags the commit but fails to push:

```
org.eclipse.jgit.api.errors.TransportException: https://charlie_hayes@bitbucket.org/charlie_hayes/turbokiva.git: Authentication is required but no CredentialsProvider has been registered
```

I changed the origin URL to be `ssh://username@host/path/repo.git` (changing `https` to `ssh`) and the gradle task successfully pushes now.

I have no idea how `git` is working with SSH creds for an HTTPS URL, or why grgit fails to use those creds.

Ideally I think grgit should should work as is, if that means re-writing the URL or wrapping it in an ssh session, that would be fine. Otherwise, maybe it could at least try those options, and if they work, present an error saying the origin should be updated.

The documentation could stand to be updated to address this.

**Comment by ajoberstar** [comment]
Hi @idontusenumbers. Sorry for the delayed response. It's not clear from your message whether you found the [authentication](http://ajoberstar.org/grgit/grgit-authentication.html) document for grgit. Could you let me know if that doc is missing the information you need?

**Comment by idontusenumbers** [comment]
I did read that and found no way to use SSH keys to authenticate HTTPS repos. I'm not well versed in the SSH key world and not sure how vanilla git handles it so maybe I'm just overlooking something.

**Comment by ajoberstar** [comment]
Grgit will authenticate based on the remote url, which is just underlying JGit behavior, same as C git.

In grgit, SSH remotes fallback to the command line ssh, so if you have a key registered in an ssh agent or a password less key it will work.

Http requires grgit to know the username and password to pass along. The underlying JGit does not support the credential helpers that cgit uses, so your cli git push working has no bearing on grgit working.

The document covers the options for passing http authentication, e.g. system properties.

Nebula release may provide other mechanisms to pass those down to grgit, but I can't speak to that.

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.

**Comment by tonyre** [comment]
@idontusenumbers It's already some time ago, please one question: 

Could you resolve this issue? I am struggling on the the exact same point.
Nebula-release-plugin creates the tag but it failed on push. 
BUT this problem only happen for "final" tagging for release candidates it worked. 
Ironically, if I push afterwards manually on the command line it works as well, but not with the gradle task: final

@ajoberstar  sorry don't know if this is the right way? ... ask or open a new issue, but wanted to connect to this thread.
