### ISSUE TITLE
Variant issue with Gradle 6.3 and 6.5.1

### ISSUE THREAD

**Issue by daystorm** [ajoberstar/grgit#324]
When attempting to use version 4.0.2, I received the following error on running it in the above listed versions of Gradle.

> Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.ajoberstar.grgit:grgit-core:4.0.2.
> Required by:
>     project :aws-util
> Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: Unable to find a matching variant of org.ajoberstar.grgit:grgit-core:4.0.2:
>   - Variant 'apiElements' capability org.ajoberstar.grgit:grgit-core:4.0.2:
>       - Incompatible attribute:
>           - Required org.gradle.jvm.version '6' and found incompatible value '8'.
>       - Other attributes:
>           - Required org.gradle.category 'library' and found compatible value 'library'.
>           - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
>           - Required org.gradle.libraryelements 'classes+resources' and found compatible value 'jar'.
>           - Found org.gradle.status 'release' but wasn't required.
>           - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
>   - Variant 'runtimeElements' capability org.ajoberstar.grgit:grgit-core:4.0.2:
>       - Incompatible attribute:
>           - Required org.gradle.jvm.version '6' and found incompatible value '8'.
>       - Other attributes:
>           - Required org.gradle.category 'library' and found compatible value 'library'.
>           - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
>           - Required org.gradle.libraryelements 'classes+resources' and found compatible value 'jar'.
>           - Found org.gradle.status 'release' but wasn't required.
>           - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
> 

It appears to run successfully on Gradle 5.6.4.

**Comment by ajoberstar** [comment]
It appears your build is using or requiring Java 6, and grgit requires Java 8.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
