### ISSUE TITLE
Support checking out paths

### ISSUE THREAD

**Issue by stefanleh** [ajoberstar/grgit#326]
Sorry for doing this by an issue but i didnt know where ask elsewhere.

Im trying to do `git checkout -- <file>` using Grgit but did not succeed yet.

What i've tried is ...

    grgit.reset(paths: [conflict])

But this seem to only affect the index but not the content of the file.
The checkout method of Grgit does not provide a way to hand over a filename, or did i miss that?

Thanks in advance,
Stefan

**Comment by ajoberstar** [comment]
This will have to be an enhancement, since that setting got left out when the checkout operation was created.

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
