### ISSUE TITLE
404 links on ajoberstar.org/grgit

### ISSUE THREAD

**Issue by rybak** [ajoberstar/grgit#328]
For example, http://ajoberstar.org/grgit/grgit-commit.html has the following:

> Returns a [Commit](http://ajoberstar.org/grgit/docs/grgit-core/groovydoc/org/ajoberstar/grgit/Commit.html) representing the new `HEAD`.

With "Commit" linking to http://ajoberstar.org/grgit/docs/grgit-core/groovydoc/org/ajoberstar/grgit/Commit.html which is a 404. Similarly [grgit-status.html](http://ajoberstar.org/grgit/grgit-status.html) links to a 404 "[Status](http://ajoberstar.org/grgit/docs/grgit-core/groovydoc/org/ajoberstar/grgit/Status.html)" page.

It seems that all "returns" sentences are affected.

**Comment by ajoberstar** [comment]
Long delayed, but links on [the updated site](https://ajoberstar.org/grgit/main/index.html) do work now (link to the source for those types instead of groovydoc, which I don't build anymore).
