### ISSUE TITLE
Classpath or conflicting dependencies

### ISSUE THREAD

**Issue by Sophon** [ajoberstar/grgit#330]
The project gradle looks like

```

buildscript {
  repositories {
    google()
    mavenCentral()
    jcenter()
  }

  dependencies {
      //some dependencies
  }
}

plugins {
    id 'org.ajoberstar.grgit' version '4.1.0'
}
```

And my module gradle has:

```
apply plugin: 'org.ajoberstar.grgit'

android {}

dependencies {

  implementation 'org.ajoberstar.grgit:grgit-gradle:4.1.0'

}
```

However, in my `Application` class I write the following:

```Kotlin
val git = Grgit.open()
```

which results in error for `open()` because `Cannot access 'groovy.lang.GroovyObject' which is a supertype of 'org.ajoberstar.grgit.Grgit'`. Check your module classpath for missing or conflicting dependencies.

So how do I fix this?

**Comment by ajoberstar** [comment]
If you're writing app code that uses grgit, then I think the issue is that pre 5.0.0 grgit-core had a compile only dependency on Groovy. You'd need to add a direct dependency on Groovy-core for this to work.
