### ISSUE TITLE
Cannot Resolve Symbol

### ISSUE THREAD

**Issue by Kranthi94** [ajoberstar/grgit#331]
Hi, 

I am using the latest version of grgit gradle plugin 'org.ajoberstar.grgit:grgit-gradle:4.0.2'. When i am using the imports of the library in the gradle file it is showing errors as **Cannot Resolve Symbol 'ajoberstar'**.

![Screenshot 2021-01-21 at 10 46 04 AM](https://user-images.githubusercontent.com/13165950/105283556-bb64b380-5bd6-11eb-9e81-7a7537aca47b.png)

**Comment by dtrunk90** [comment]
Same. Project compiles without issues but IDE complains.
IDE info:
```
IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-38-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 36
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (50.1.0), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), com.chrisrm.idea.MaterialThemeUI (6.9.1)
Kotlin: 212-1.5.31-release-546-IJ4638.7
Current Desktop: Budgie:GNOME
```

**Comment by ajoberstar** [comment]
I would expect something like the Intellij sync be inng the issue here. You can reopen if that's not the case.
