### ISSUE TITLE
Remove `buildFinished` listener in order to support gradle configuration-cache

### ISSUE THREAD

**Issue by simschla** [ajoberstar/grgit#333]
As of 4.1.0, the plugin adds a `Gradle.buildFinished` listener, which makes it incompatible with gradle's  configuration cache.

In my build I get the following output when grgit is applied while `configuration-cache=true` is enabled:

```
FAILURE: Build failed with an exception.

* Where:
Build file '[...]/build.gradle' line: 8

* What went wrong:
Configuration cache problems found in this build.

4 problems were found storing the configuration cache, 3 of which seem unique.
[ redacted the problems of our own build files]
- Plugin 'org.ajoberstar.grgit': registration of listener on 'Gradle.buildFinished' is unsupported
  See https://docs.gradle.org/6.8.1/userguide/configuration_cache.html#config_cache:requirements:build_listeners

See the complete report at file:[...]/configuration-cache-report.html
```

Would be nice if this could be changed - which seems to be straightforward using a [BuildService](https://docs.gradle.org/6.8.1/userguide/build_services.html#build_services)

**Comment by simschla** [comment]
Problematic portion seems to be:
https://github.com/ajoberstar/grgit/blob/13860c95a0d8ff0960e2d2eb60288718c3336655/grgit-gradle/src/main/groovy/org/ajoberstar/grgit/gradle/GrgitPlugin.groovy#L20-L23

**Comment by abelom** [comment]
Related/duplicate of #322?

@simschla are you saying that GrGit is moving _away_ from configuration-cache?

**Comment by simschla** [comment]
Duplicate of #322

**Comment by abelom** [comment]
@simschla see #353
