### ISSUE TITLE
Maintenance and kotlin rewrite

### ISSUE THREAD

**Issue by elect86** [ajoberstar/grgit#336]
Hey Andrew,

really nice lib, kudos!

Anyway, I ported grgit to kotlin ([here](https://github.com/elect86/gik)), and I did that for different reasons. 

The first one is essentially because of debugging: I'm gonna play with it extensively in the next future and  `operations` are implemented directly as methods, which makes it much easier when debugging step by step.

Moreover, you get all the benefits of a statically typed language without the verbosity of java, this mean much bigger support from the IDE, completion and navigation in primis.

Last but not least, I also rewrote it in order to get much more familiar with it

Since you are not spending any more much time on this cool project, in the case you are willing to accept the rewrite, I'd be more than happy to create a PR (and refractor packages and classes to your path, that is `org.ajoberstar.grgit` instead  of `gik` -something quick I came up with-)

Cheers

**Comment by dapp** [comment]
Are you going to publish this?  I can't get grgit working from my kotlin build script, and would love to use this instead?

**Comment by elect86** [comment]
> Are you going to publish this? I can't get grgit working from my kotlin build script, and would love to use this instead?

Sure, I'll do it in the next days

**Comment by dapp** [comment]
@elect86  Any update on this?  I can't get the original groovy plugin working from the kotlin gradle DSL, so I can't convert my scripts until I get this plugin.  I'm happy to build and publish it for you, if you want.

**Comment by elect86** [comment]
This evening I'll make it

**Comment by dapp** [comment]
I haven't used it yet, since it isn't published.   I'll wait until M onday, but then I'll have to fork and publish my own version so I can use it.  I don't mean to create work for you to do, but I need a kotlin jgit wrapper, and this is the only one I've seen.

Please post back here if you get around to publishing, otherwise I'll build and publish on Monday.  Thanks

**Comment by elect86** [comment]
You don't need to wait the publishing to use it:
`build.gradle.kts`
```
plugins {
    id("gik")
}
```
`settings.gradle.kts`:
```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if(requested.id.id == "gik")
                useModule("com.github.elect86:gik:8e46870")
        }
    }
    repositories {
        gradlePluginPortal()
        maven("https://jitpack.io")
    }
}
```

**Comment by elect86** [comment]
Plugin is submitted for approval though

**Comment by elect86** [comment]
@dapp [approved](https://plugins.gradle.org/plugin/elect86.gik)

**Comment by ajoberstar** [comment]
Since this project is specifically a Groovy wrapper for JGit I don't think it makes sense to merge in a Kotlin rewrite. Certainly seems reasonable to have a Kotlin based alternative, so I wish you success with that. There's more water running towards Kotlin that Groovy these days.
