### ISSUE TITLE
grgit-core uses latest.release of jgit

### ISSUE THREAD

**Issue by hborham** [ajoberstar/grgit#339]
jgit 6.+ is released and is compiled using java 11.   as a result, some repos have jgit 6.+ currently and using latest.release will cause a java 11 library to be pulled in as a transitive dependency.  

`A problem occurred configuring project ''.
   > Failed to notify project evaluation listener.
      > org/eclipse/jgit/errors/RepositoryNotFoundException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by KENNYSOFT** [comment]
Found out https://github.com/n0mer/gradle-git-properties Gradle plugin is also broken with running Gradle in Java under 11.

**Comment by jjoslet** [comment]
A workaround is to fix the jgit dependency in your pom.xml:
```
<dependency>
	<groupId>org.eclipse.jgit</groupId>
	<artifactId>org.eclipse.jgit</artifactId>
	<version>5.9.0.202009080501-r</version>
</dependency>
```

**Comment by stefannegele** [comment]
A downgrade to 4.0.2 worked for me.

**Comment by chkpnt** [comment]
Workaround until 4.1.1 is available:

```
buildscript {
  repositories { mavenCentral() }
  dependencies {
    // TODO, Gregor, 30.11.2021: Check, if workaround for https://github.com/ajoberstar/grgit/issues/339 is still needed
    classpath("org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r") {
      force = true
    }
  }
}

...
```

But I'm confused: There is no JGit 6 on Maven Central? 5.13 is the latest version, which works fine with Java 8.

**Comment by hborham** [comment]
> Workaround until 4.1.1 is available:
> 
> ```
> buildscript {
>   repositories { mavenCentral() }
>   dependencies {
>     // TODO, Gregor, 30.11.2021: Check, if workaround for https://github.com/ajoberstar/grgit/issues/339 is still needed
>     classpath("org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r") {
>       force = true
>     }
>   }
> }
> 
> ...
> ```
> 
> Btw, you can look up the dependency graph for your build script with the task `buildEnvironment`:
> 
> ```
> > Task :buildEnvironment
> ...
> classpath
> +--- org.eclipse.jgit:org.eclipse.jgit:5.13.0.202109080827-r
> |    +--- com.googlecode.javaewah:JavaEWAH:1.1.12
> |    \--- org.slf4j:slf4j-api:1.7.30
> +--- org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:4.1.0
> |    \--- org.ajoberstar.grgit:grgit-gradle:4.1.0
> |         \--- org.ajoberstar.grgit:grgit-core:4.1.0
> |              \--- org.eclipse.jgit:org.eclipse.jgit:latest.release -> 5.13.0.202109080827-r (*)
> ...
> ```
> 
> But I'm confused: There is no JGit 6 on Maven Central? 5.13 is the latest version, which works fine with Java 8.

See https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml and https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/6.0.0.202111291000-r/

**Comment by chkpnt** [comment]
Ah, I see. Then it's only a caching issue on mvnrepository.com.

![image](https://user-images.githubusercontent.com/1956979/144111568-1b39c13a-3311-4ef3-bc33-b84691bd7fd4.jpeg)

**Comment by ajoberstar** [comment]
I believe 4.1.1-rc.4 is published to Maven Central now. It may take some time to propagate through (I have closed and released the staging repo in oss.sonatype.org). Can someone confirm is this resolves your issue and then I'll make the final 4.1.1 release?

**Comment by douph1** [comment]
>Can someone confirm is this resolves your issue and then I'll make the final 4.1.1 release

4.1.1-rc.4 works great for me with jdk8 and without the workaround

**Comment by hborham** [comment]
ditto, 4.1.1-rc.4 resolves the jgit issue on our side as well.   🙇 for fixing so quickly!

**Comment by chirag4semandex** [comment]
Can someone please share where can I find the 4.1.1-rc.4 version? I dont see it at https://mvnrepository.com/artifact/org.ajoberstar.grgit/grgit-core

**Comment by ajoberstar** [comment]
It seems like mvrepository.com and search.maven.org take a little longer to catch up. But it's out in the actual repo: https://repo1.maven.org/maven2/org/ajoberstar/grgit/grgit-core/

**Comment by evol-hulft** [comment]
Thanks for fix!

**Comment by stebbi** [comment]
Thanks for the fix Andrew!

**Comment by alvaroinfantedemoraes** [comment]
Hello, thanks for the fix. It was solved for our project using this dependency.
