### ISSUE TITLE
Latest release of grgit is not backward jdk compatible 

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [ajoberstar/grgit#348]
When application using grgit running on JDK8 started failing from this week with below error

org/eclipse/jgit/errors/RepositoryNotFoundException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by ramakrishnakaushik97** [comment]
We are using org.ajoberstar.grgit:grgit-gradle:4.1.0 version from last 6 to 8 months. Was any changes done to the existing 4.1.0 version ?

**Comment by ajoberstar** [comment]
See #339, this was fixed in 4.1.1
