### ISSUE TITLE
Unsupported major.minor version

### ISSUE THREAD

**Issue by gorje001** [ajoberstar/grgit#35]
I'm trying to just open the repo and I get the error.  Are there certain requirements on the repo? Here is the code in build.gradle.

import org.ajoberstar.grgit.*
ext.repo = Grgit.open(project.file('.'))

Error:Cause: org/ajoberstar/grgit/Grgit : Unsupported major.minor version 51.0

**Comment by facewindu** [comment]
Why does grgit require Java 7 runtime or higher ?
I looked at the code, and it seems everything is java 6 compliant except the import "java.nio.file.Path" in "org.ajoberstar.grgit.util.CoercionUtil.groovy"

Maybe a java-6 compliant code could be invoked instead ?
Unfortunately my company still used java 6 code, and it's a shame we can't use grgit.

What do you think of this analysis ?

**Comment by ajoberstar** [comment]
From memory, I believe that is the only use of Java 7. My rationale at the time was that I wanted to reserve the right to use Java 7 APIs more widely without making a major version jump.

I entirely get that many people are in situations where it is difficult to use newer JDKs. However, I want to focus my time on newer JDK versions. Given that Oracle has already dropped Java 7 support, I'm hoping companies beginning trending towards staying up to date.

**Comment by facewindu** [comment]
ok, thanks for the quick reply. I can't really blame you for that :) I will probably use an internal recompiled grgit version without the Path call in CoercionUtil. It will only force me to use File or String (and not pP) for the patch / dir variable in ApplyOp / CloneOp / InitOp / OpenOp, which is not a big deal.

**Comment by natea** [comment]
I'm also encountering this error when I open my Android project in Android Studio.
```
Error:Cause: org/ajoberstar/grgit/Grgit : Unsupported major.minor version 51.0
```

I have Java 8 installed:

```
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

And Gradle is 2.5:

```
$ gradle -v

------------------------------------------------------------
Gradle 2.5
------------------------------------------------------------

Build time:   2015-07-08 07:38:37 UTC
Build number: none
Revision:     093765bccd3ee722ed5310583e5ed140688a8c2b

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.10.4 x86_64
```

Do I need to set $JAVA_HOME in my environment?

**Comment by ajoberstar** [comment]
I'm not familiar with how Android Studio works, but you may just need to determine how to change the version it runs with and/or the version it executes Gradle under.

**Comment by natea** [comment]
I fixed the error by telling Android Studio to use a newer version of Java.

**Comment by ajoberstar** [comment]
Great. Thanks for posting back.

**Comment by rhussmann** [comment]
Thanks for this thread and solution. Solved my problem. Appreciate it.
