### ISSUE TITLE
back-port configuration cache support to 4.x branch i.e. java 8

### ISSUE THREAD

**Issue by abelom** [ajoberstar/grgit#355]
I know it's ridiculous but at my place we are still 9 months away from java 11.

is there any chance to have 4.xx with configuration cache support and same old JGit meaning same old java 8?

**Comment by ajoberstar** [comment]
While it may not be possible in your environment, you can run Gradle under 11+ and use the java.toolchain block to use Java 8 to compile and run your app. So as long as you can put Java 11 on developer workstations and CI, you don't have to migrate your applications off of 8.

Barring that, I think a backport is on the table, but I would want to maintain the same Gradle compatibility grgit 4 has now.

My near term focus is updating my other plugins to the latest Gradle capabilities, so I'm not sure when I'd be able to look at this.

**Comment by ajoberstar** [comment]
Given #356 which means the build cache support fails on (many?) multi-project builds, I won't be porting this to 4.x. When Gradle resolves the issue in (hopefully) 7.5, feel free to nudge me again to get this ported.

**Comment by ajoberstar** [comment]
No plans to backport this, so I'm going to close this.
