### ISSUE TITLE
Wrong JCenter note in readme

### ISSUE THREAD

**Issue by Vampire** [ajoberstar/grgit#357]
It is long known that JCenter will not be shut down, but will be available read-only.
I'd recommend you remove the note regarding that from the readme.

**Comment by ajoberstar** [comment]
If you have a suggestion for more accurate wording, feel free to send a PR. I haven't kept up on JCenter's new status.

**Comment by Vampire** [comment]
My suggestion was and is to just remove the paragraph. JCenter stays read-only (unless JFrog changes mind of course), so the old versions will just continue to work like they used to. And if they really switch it off, I'd probably expect Gradle to mirror the plugin artifacts before to not break builds in the wild.
