### ISSUE TITLE
Wrong / missing information regarding maxParallelUsages in the readme

### ISSUE THREAD

**Issue by Vampire** [ajoberstar/grgit#360]
The readme recommends setting `maxParallelUsages` to `1` when registering an own build service.
The plugin also sets this value to `1` for the service it registers itself.

**But** this setting has exactly ZERO effect on its own.
Only tasks that are registered as users of that build service using `Task#usesService(Provider<? extends BuildService<?>>` actually count towards this limit as Gradle does not magically guess which tasks is using the service just by the set properties.
If only this property is set, the service can still be used in parallel by as many tasks as are run in parallel.

**Comment by ajoberstar** [comment]
Thanks for pointing that out. I'll reread the docs and correct the readme (and a few usages in my plugins).
