### ISSUE TITLE
Support checkout from specific commit hash

### ISSUE THREAD

**Issue by Soulrealz** [ajoberstar/grgit#365]
Hello currently you can check out from different branches however you cannot checkout from a specific commit hash. It would be really useful if you could checkout to an older commit in case you want to see older behaviour and compare differences in case something goes wrong. There are probably more applications I can't think of right now. Is it possible to implement this?

**Comment by ajoberstar** [comment]
It looks like JGit's [CheckoutCommand](https://download.eclipse.org/jgit/site/6.2.0.202206071550-r/apidocs/org/eclipse/jgit/api/CheckoutCommand.html#setName(java.lang.String)) `setName()` does accept commit hashes. This may "just work" if you pass in a commit hash as a string. If you're getting an error while doing this, please post stack trace.

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
