### ISSUE TITLE
Version 5.0.0 missing from the Gradle Plugin Repository

### ISSUE THREAD

**Issue by LajosCseppento** [ajoberstar/grgit#366]
Version 5.0.0 seems missing from the Gradle Plugin Repository. It is available in Maven Central.

* https://mvnrepository.com/artifact/org.ajoberstar.grgit/org.ajoberstar.grgit.gradle.plugin
* https://mvnrepository.com/artifact/org.ajoberstar.grgit/org.ajoberstar.grgit.gradle.plugin?repo=gradle-plugins
* https://plugins.gradle.org/plugin/org.ajoberstar.grgit

**Comment by ajoberstar** [comment]
This is intentional. See #359 and the README.

**Comment by LajosCseppento** [comment]
Sorry I missed it. Totally OK, it was a little bit confusing that it was rc3 on Plugin Portal and there is a newer version on Maven Central (maybe try to do a last release with updated description to not look there?). In our enterprise use case it is totally fine, anyway we have a virtual repo built from Maven Central, Gradle Plugin portal and our internal business.
