### ISSUE TITLE
Can't find Grgit on my custom class plugin

### ISSUE THREAD

**Issue by robercoding** [ajoberstar/grgit#367]
Hi! 
First of all I'd like to clarify that I'm not expert when it comes to gradle/custom plugins, I just started and I'm trying a bunch of different things. One of those things that I'm trying is to use grgit inside a custom class plugin

![image](https://user-images.githubusercontent.com/66839423/179373115-5d8de499-ec35-4c63-b196-5e3305c2aa1b.png)

As you can see, I can't find Grgit in the class. But if I create a task in my build.gradle.kts file then it shows up, and grgit is working as expected!
But I want to move it out to a custom plugin class

Here's the plugin that I'm implementing
```
plugin {
     id("org.ajoberstar.grgit.service") version "5.0.0"
}
```
Jdk: **11**
Gradle: **7.0**
I've tried a bunch of different Jdk/Gradle just in case and doesn't seem to work

Is there anything that I could be missing? Feel free to point out/ask anything, as I said I'm learning!

**Comment by ajoberstar** [comment]
Sorry for the delayed response. If you're developing a plugin, you want to add grgit as a project dependency, rather than to the plugins.

For example:

```groovy
implementation("org.ajoberstar.grgit:grgit-gradle:5.0.0")
```

Please reopen if this doesn't solve your issue.
