### ISSUE TITLE
unable to pass config settings when cloning

### ISSUE THREAD

**Issue by jscancella** [ajoberstar/grgit#369]
currently I don't see a way to do the equivalent in grgit `git clone [repository] –config core.autocrlf=false`. This affects me because I have a git repo that must be checked out with the original line endings on windows, but all my other repos don't require this and it cause me great pain to turn it off globally.

I am hoping for something like the below where I can pass in a list of key value pairs to configure the git config:
```
Grgit.clone(dir: location, 
                  uri: 'https://github.com/libraryofcongress/bagit-conformance-suite.git',
                  config: [{'core.autocrlf': false}])
```

**Comment by ajoberstar** [comment]
It doesn't look like that's an option on the JGit `CloneCommand`, so not sure if there's any other way through JGit's API to make that happen.

https://download.eclipse.org/jgit/site/6.2.0.202206071550-r/apidocs/org/eclipse/jgit/api/CloneCommand.html
