### ISSUE TITLE
Move artefacts from jcenter

### ISSUE THREAD

**Issue by dosier** [ajoberstar/grgit#376]
JCenter no longer seems to work as a repository, getting the following:
```
A problem occurred configuring root project 'MyProject'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.eclipse.jgit:org.eclipse.jgit:latest.release.
     Required by:
         project : > org.ajoberstar.grgit:grgit-core:4.1.0
      > Failed to list versions for org.eclipse.jgit:org.eclipse.jgit.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml'.
               > Read timed out
```

**Comment by yaboong** [comment]
You seem to be using 4.1.0.
I think you need to [update the version to 4.1.1](https://github.com/ajoberstar/grgit#newest-versions-are-on-maven-central) 
> As of 4.1.1, grgit is published to Maven Central and the Gradle Plugin Portal.

or [do this](https://github.com/ajoberstar/grgit#old-versions-from-bintrayjcenter)
```
maven {
  name = 'ajoberstar-backup'
  url = 'https://ajoberstar.org/bintray-backup/'
}
```

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
