### ISSUE TITLE
Version 4.02 not in Maven Central

### ISSUE THREAD

**Issue by pe** [ajoberstar/grgit#377]
It seems that older Versions disappeared from Maven Central.

See https://search.maven.org/artifact/org.ajoberstar.grgit/grgit-core
![Bildschirm­foto 2022-11-08 um 09 47 48](https://user-images.githubusercontent.com/61654/200517858-2228d855-b91e-44ba-826d-f04c626be8c3.png)

**Comment by thomaslundstrom** [comment]
Same with version 3.0.0.

**Comment by AkselAllas** [comment]
This is a big problem :)

**Comment by pe** [comment]
Just did RTFM. (See Readme.md

> [Newest versions are on Maven Central](https://github.com/ajoberstar/grgit#newest-versions-are-on-maven-central)
> As of _4.1.1_, grgit is published to Maven Central and the Gradle Plugin Portal.

> [Old versions from Bintray/JCenter](https://github.com/ajoberstar/grgit#old-versions-from-bintrayjcenter)

But gradle has an issue with mirroring https://status.gradle.com/?utm_source=embed

**Comment by dmurat** [comment]
If you don't have upgraded dependency (as for nebula-release-plugin mentioned above) available, you can either add `jcenter()` in the repository list of a buildscript
```
buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    jcenter()
  }
}

plugins {
...
}
```
or enforce dependency upgrade to 4.1.1 version

```
buildscript {
  configurations.all {
    resolutionStrategy {
      force "org.ajoberstar.grgit:grgit-core:4.1.1"
    }
  }
}

plugins {
...
}
```

HTH
