### ISSUE TITLE
error : git-upload-pack not permitted on <git repo>

### ISSUE THREAD

**Issue by Joonkkyo** [ajoberstar/grgit#378]
I used grgit plugin as 'org.ajoberstar.grgit' version '4.1.1',
and when I tried to clone other git (enterprise) repository using grgit, I faced with this error.

```
A problem occurred evaluating root project 'sapphire-back-avas'.
> https://github.ecodesamsung.com/VD-SmartTVServer/sapphire-back-core.git: git-upload-pack not permitted on 'https://github.ecodesamsung.com/VD-SmartTVServer/sapphire-back-core.git/'
```

I checked my PAT and environment variables (GRGIT_USER, GRGIT_PASS) and that works well in other computer.
But this error only occurs in my local pc so I can't find how I can solve this issue.
so, is there anything I have to check in terms of using grgit?
I'm looking forward to your reply.

Thanks!

**Comment by ajoberstar** [comment]
Brief searching I did on this topic suggested it's due to GitHub deprecating password authentication. If you're using a PAT instead of a password, I'm not sure if that's the issue though.

https://webfuse.in/blogs/git-upload-pack-not-permitted-on-error-while-git-pull-and-git-push/
