### ISSUE TITLE
Support for `Provider` in `org.ajoberstar.grgit.service.ResolveService#toRevisionString`

### ISSUE THREAD

**Issue by Vampire** [ajoberstar/grgit#383]
If you for example do `includes.add(release.git.requireBranch)` in a `log` call, you get an exception
> Can't handle the following object (property(java.lang.String, fixed(class java.lang.String, master))) of class (class org.gradle.api.internal.provider.DefaultProperty)

Would be nice if the mentioned method would support the supported types also if wrapped in a Gradle `Provider` by unwrapping it.

**Comment by ajoberstar** [comment]
Can understand the use case, but I do not plan to add Gradle types into the `grgit-core` library.
