### ISSUE TITLE
Could hub4j help the Git Server interaction?

### ISSUE THREAD

**Issue by aadrian** [ajoberstar/grgit#388]
Hi,

Could https://github.com/hub4j/github-api   https://github-api.kohsuke.org/ _(based on JGit too)_ help and simplify the interaction with GIT servers? e.g. for this plug-in or other dependent plug-ins ?

`hub4j` is used by GitBicket too https://gitbucket.github.io/  (for compatibility with the GitHub).

Thank you.

**Comment by ajoberstar** [comment]
I've used hub4j before on other projects, but what portion of the interaction are you looking to simplify in grgit?
