### ISSUE TITLE
Unable to publish release with org.ajoberstar.grgit version '5.2.0'

### ISSUE THREAD

**Issue by yochanah** [ajoberstar/grgit#393]
Hi There,

Recently upgraded our project stack to Java 11 and Gradle 7.1.1

When we try to publish release with below command :
/gradlew -Porg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Porg.ajoberstar.grgit.auth.password release

We are getting below error :
**No such property: branch for class: org.ajoberstar.grgit.operation.BranchStatusOp**

We are using :     id 'org.ajoberstar.grgit' version '5.2.0'

Need assistance to troubleshoot this issue.

Many Thanks !

**Comment by ajoberstar** [comment]
The branch status operation has a `name` property not a `branch` property, so that's most likely what's going wrong. 

https://github.com/ajoberstar/grgit/blob/main/grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/BranchStatusOp.groovy
