### ISSUE TITLE
Support: Recomended way to check if in git directory.

### ISSUE THREAD

**Issue by spacey-sooty** [ajoberstar/grgit#397]
I have a Gradle plugin that will log extra data related to git info if within a git directory. What would be the recomended way to check this?

**Comment by ajoberstar** [comment]
In your plugin, you could do something like:

```java
try {
  var grgitExtension = project.getExtensions().getBytType(GrgitServiceExtension.class);
  var grgit = grgitExtension.getService().getGrgit();
  // if it exists
} catch (IllegalStateException e) {
  // if no git repo
}
```

**Comment by spacey-sooty** [comment]
Would something like
```groovy
try {
  var grgit = Grgit.open();
} catch (Exception e) {
}
```
Also work?

**Comment by ajoberstar** [comment]
Yes, just be mindful of the behavior of Grgit.open with no args. Generally this wouldn't be an issue, but Gradle historically didn't guarantee the working directory matches the project directory, so it could cause it to find the wrong Git repo.

https://ajoberstar.org/grgit/main/grgit-open.html
