### ISSUE TITLE
Feature: Support `git rev-parse`

### ISSUE THREAD

**Issue by spacey-sooty** [ajoberstar/grgit#398]
Could be a solution to #397

**Comment by ajoberstar** [comment]
The [resolve](https://ajoberstar.org/grgit/main/grgit-resolve.html) API might be the closest to a rev-parse equivalent.

**Comment by spacey-sooty** [comment]
Thanks for the prompt response!
I believe this will fix most of the things I am missing without rev-parse but due to not being able to pass in more specific arguments it still misses a few features most notable `git rev-parse --is-inside-work-tree` which would be the simplest solution to #397 imo

**Comment by spacey-sooty** [comment]
I'm also getting an error that resolve is private within Grgit...

**Comment by ajoberstar** [comment]
If you're coming from Java it may require `grgit.getResolve()`. 

The default visibility in Groovy is public, so adding it explicitly like in your #398 shouldn't change anything.

**Comment by spacey-sooty** [comment]
Ohhb ok that my mistake, thanks!
