### ISSUE TITLE
git branch name

### ISSUE THREAD

**Issue by paleozogt** [ajoberstar/grgit#40]
There doesn't seem to be a way to access the current branch name, e.g.:
`git rev-parse --abbrev-ref HEAD`

This is super-useful for projects that include the branch-name in their versioning.

**Comment by yogurtearl** [comment]
Seems to now be `grgit.branch.getCurrent()`

**Comment by tgkprog** [comment]
And in a gradle file to get the rev id and branch.

`Branch : ${Grgit.open(dir: '.').branch.getCurrent().fullName}` 

More info here [https://gist.github.com/tgkprog/4923284aacd68480d232b42c1239c529](https://gist.github.com/tgkprog/4923284aacd68480d232b42c1239c529) (copied from a stackoverflow and addd branch name)

**Comment by ajoberstar** [comment]
As of 2.0.0 the `.getCurrent()` is deprecated and the preferred usage is `grgit.branch.current()`.
