### ISSUE TITLE
if .git directory is missing we get: Unresolved reference: grgit

### ISSUE THREAD

**Issue by zoff99** [ajoberstar/grgit#400]
if using grgit.branch.current().fullName for example and there is no .git directory then the following error occurs:
Unresolved reference: grgit

i can't catch it with try/catch

**Comment by zoff99** [comment]
https://github.com/Zoxcore/trifa_material/issues/199

**Comment by zoff99** [comment]
https://github.com/Zoxcore/trifa_material/blob/ea6a709f3c16cf043137963d1ae451db036b29f7/build.gradle.kts#L39

**Comment by ajoberstar** [comment]
I believe you're running into https://github.com/ajoberstar/grgit/issues/361, which is a limitation of this Groovy-focused plugin when used in a Kotlin build script. I don't currently have any plan to do anything with this, but you can add watch the other issue in case there are updates or further discussion.
