### ISSUE TITLE
Could not find grgit-core-4.0.1.jar

### ISSUE THREAD

**Issue by seebigsea** [ajoberstar/grgit#404]
Current Behavior
When use Idea with gradle 6.8.3 to build our project, got error: Could not find grgit-core-4.0.1.jar (org.ajoberstar.grgit:grgit-core:4.0.1)
Searched in the following locations:
https://plugins.gradle.org/m2/org/ajoberstar/grgit-core/4.0.1/grgit-core_4.0.1.jar
And we checked repo.maven.apache.org/maven2/org/ajoberstar/grgit/grgit-core/
the min version is 4.1.1
Does 4.0.1 deleted？

Expected Behavior
Should can download from https://plugins.gradle.org/m2/org/ajoberstar/grgit-core/4.0.1/grgit-core_4.0.1.jar

**Comment by ajoberstar** [comment]
See this note in the readme.

https://github.com/ajoberstar/grgit?tab=readme-ov-file#newest-versions-are-on-maven-central

**Comment by seebigsea** [comment]
> See this note in the readme.
> 
> https://github.com/ajoberstar/grgit?tab=readme-ov-file#newest-versions-are-on-maven-central

Thank you so much!
We checked our project and find that one plugin https://github.com/vlsi/vlsi-release-plugins which uesed grgit, so we just upgrade this is ok.

**Comment by seebigsea** [comment]
> See this note in the readme.
> 
> https://github.com/ajoberstar/grgit?tab=readme-ov-file#newest-versions-are-on-maven-central

Thank you so much!
We checked our project and find that one plugin https://github.com/vlsi/vlsi-release-plugins which uesed grgit, so we just upgrade this is ok.

**Comment by seebigsea** [comment]
> See this note in the readme.
> 
> https://github.com/ajoberstar/grgit?tab=readme-ov-file#newest-versions-are-on-maven-central

Thank you so much!
We checked our project and find that one plugin https://github.com/vlsi/vlsi-release-plugins which used grgit, so we just upgrade this is ok.

**Comment by seebigsea** [comment]
fixed
