### ISSUE TITLE
Missing grgit 1.9.3

### ISSUE THREAD

**Issue by toxn** [ajoberstar/grgit#405]
I noticed `grgit` 1.9.3 is absent from any repo as it is a dependency of your legacy `release-opinion` gradle plugin. Could you re-release it so that legacy projects can build?

**Comment by ajoberstar** [comment]
I have no plans to re-release any old versions of the plugin.

You can see information in the readme about workarounds to get at older versions: https://github.com/ajoberstar/grgit?tab=readme-ov-file#finding-versions-of-grgit
