### ISSUE TITLE
Add remote operations

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/grgit#5]
- [ ] Remote Add
- [ ] Remote Remove
- [ ] Remote List

**Comment by breskeby** [comment]
I can give you a usecase: bamboo checkout does not include the correct remote repository. so before you can work reference the correct remote, first you must declare it.

**Comment by ajoberstar** [comment]
Sounds good

**Comment by joanmarian** [comment]
+1

**Comment by ajoberstar** [comment]
Woops... forgot add/list are already in place. Probably don't need remove, so I'll close this again.
