### ISSUE TITLE
Support for add --all

### ISSUE THREAD

**Issue by kenzierocks** [ajoberstar/grgit#53]
One of the most important features I use in git is `add --all`, which removes files that have been deleted from the index. This can technically be simulated with `remove --cached -r .` followed by `add`, but running one operation is better than two.

**Comment by ajoberstar** [comment]
JGit's [AddCommand](http://download.eclipse.org/jgit/site/3.7.0.201502260915-r/apidocs/org/eclipse/jgit/api/AddCommand.html) doesn't have the all option. 

Since `grgit` is intended to be a subset of JGit with a friendlier API, I don't plan on implementing features not supported by JGit.

**Comment by kenzierocks** [comment]
Alright, I'll wait for that.

**Comment by lbergelson** [comment]
If you file a ticket with jgit they would probably add in the requested
option.    I requested an option for git describe a week ago and it looks
like it will be going into a version soon.

**Comment by AyalCiobotaru** [comment]
Was this implemented?

**Comment by ajoberstar** [comment]
It was not. As far as I know there's no JGit issue open for this.
