### ISSUE TITLE
Add support for tree in Commit

### ISSUE THREAD

**Issue by ki82** [ajoberstar/grgit#58]
We would need to get the info about the tree in git since we use gerrit/zuul which merges and the tree is the only unique identifier.

git cat-file -p HEAD
shows the tree info among other information.

My usecase is:
grgit.head().tree

**Comment by ki82** [comment]
Adding 300$ in sponsoring for this issue if it gets done quick, otherwise I would need to implement it myself.

https://freedomsponsors.org/issue/665/add-support-for-tree-in-commit

**Comment by ajoberstar** [comment]
My current plans are to keep grgit limited to porcelain-type commands, so I wouldn't see tree fitting in with this. You do have access to JGit directly through `grgit.repository.jgit` which will return an instance of `org.eclipse.jgit.api.Git`.
