### ISSUE TITLE
SSh authentication without ssh-agent

### ISSUE THREAD

**Issue by facewindu** [ajoberstar/grgit#63]
I'm trying to connect to a remote repository managed with Gitolite, with a generic username "git" (shared by everyone).
The gitolite instance checks its keys, for a match regarding my id_rsa private key.
This works fine with Jgit (using Eclipse Egit plugin) probably because Eclipse "knows" where to find the ssh keys (thanks to the SSH2 configuration section on Eclipse preferences ?)

When trying to use grgit from a Gradle project, I can't manage to push to the remote repo. Using debug output, it shows that I don't have ssh-agent nor pageant available (which is true).

I found this article http://www.codeaffine.com/2014/12/09/jgit-authentication/
that explains how to use SSH with JGit.

I'm not a pro with SSH, but would something like that be possible in grgit ?
If JGit can connect to a remote repo with SSH private/public keys, and without sshagent, could grgit do the same ?

**Comment by ajoberstar** [comment]
Yes, this should definitely be possible. I'll add it to the list.

**Comment by ajoberstar** [comment]
Can you try 1.3.0-milestone.2 to see if this resolves the issue for you?

Specify the location of your private key with the following system property: `org.ajoberstar.grgit.auth.ssh.private`.

**Comment by facewindu** [comment]
And this one is OK as well.
Small remark though
My id_rsa private key is in a very regular location : %USERPROFILE%\.ssh\id_rsa

If I specify  -Dorg.ajoberstar.grgit.auth.ssh.private=%USERPROFILE%\.ssh\id_rsa, it works (so your part is perfect :))
But since the location is regular, I thought that Jgit would automatically look for it and set my identity, if found

**Comment by ajoberstar** [comment]
Yeah, I would have thought it would pick up that location.

I'm releasing 1.3.0 right now. Thanks for the quick verifications on all of these issues.
