### ISSUE TITLE
log does not work with annotated tags

### ISSUE THREAD

**Issue by tschulte** [ajoberstar/grgit#71]
given: 'a git repository with a tag'
```bash
cd /tmp/
mkdir grgit
cd grgit/
git init
git commit --allow-empty -m '.'
git tag -m '.' v1.0.0
```

when: 'I have the following groovy script'
```groovy
@Grab('org.ajoberstar:grgit:1.3.0')
import org.ajoberstar.grgit.Grgit
def grgit = Grgit.open()
grgit.log {
    range 'v1.0.0', 'HEAD'
}.each { println it.id }
```
an Exception is thrown

Caught: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object 6b291bb71a1b2372323fdfbb24a408b62248303e is not a commit.

I tried

```groovy
def grgit = Grgit.open()
grgit.log {
    def tag = JGitUtil.resolveTag(grgit.repository, 'v1.0.0')
    range tag, 'HEAD'
}.each { println it.id }
```
without success.

It does only work, if I change it to 

```groovy
def grgit = Grgit.open()
grgit.log {
    def tag = JGitUtil.resolveTag(grgit.repository, 'v1.0.0')
    range tag.commit, 'HEAD'
}.each { println it.id }
```

There is no problem with simple (non-annotated) tags.

**Comment by ajoberstar** [comment]
I think I've seen that before, but I didn't look too much into it. The workaround I was using was:

```groovy
grgit.log {
  range 'v1.0.0^{commit}', 'HEAD'
}.each { println it.id }
```

Does that work for you? Either way I'll probably add it to the wishlist, just to see if there's a better way to handle this.

**Comment by tschulte** [comment]
Yes, that does the trick. I was not aware of that syntax. As Lothar Matthäus would say: Again what learned. (https://www.youtube.com/watch?v=fH55rwgx1nY)

But I had to write `range "${previousVersionString}^{commit}".toString(), 'HEAD'` in my code, because ResolveService.toRevisionString does not support GStrings. Maybe that's another enhancement ticket?

**Comment by ajoberstar** [comment]
Yes, the GString stuff should be enhanced (#72). 

I'm guessing there's some trick to resolving the right type of object (in the grgit code) to use in the log that would avoid needing to add the `^{commit}` at the end.
