### ISSUE TITLE
Support for submodules

### ISSUE THREAD

**Issue by ki82** [ajoberstar/grgit#73]
Grgit fails to open submodules with "repository not found:", since there is no .git directory in a submodule.

In a submodule there is an .git file that in my example looks like this:
gitdir: ../.git/modules/subModuleFolder
If I use Grgit.open(' ../.git/modules/subModuleFolder') it seems to work fine.

It would be nice if grgit could internally read .git file in a submodule and then parse which git directory to use.

**Comment by ki82** [comment]
200$ is up for grabs for solving this at: https://freedomsponsors.org/issue/730/support-for-submodules

**Comment by ajoberstar** [comment]
Have you tried any of the [new options](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/OpenOp.html) introduced in 1.3.0? These fixed #64 and #66, which may be similar to the issue you're having.

**Comment by ki82** [comment]
Thanks, it worked by using the currentDir option
