### ISSUE TITLE
Not Showing Rename Files

### ISSUE THREAD

**Issue by Scuilion** [ajoberstar/grgit#74]
I can't seem to get `grgit.show(id)` to display the renamed files.

Running `git log -M --summary` outputs:

```

commit 4eec35b7dc52df0e710799c5805be27a928b49a6
Author: kevin <oneal.kevin@gmail.com>
Date:   Fri Aug 21 14:55:21 2015 -0500

    moving

    add read me

 rename originName => newName (100%)
```

but when I do `git.show(id)` it does not show any renamed files. What am I missing?

You can see the situation in this [repo](https://github.com/Scuilion/grgit-issue-rename)
Just run `./gradlew checkRename'

**Comment by ajoberstar** [comment]
I don't believe the JGit API provides renamed files in it's status command. If that's true, I wouldn't try to include that in `grgit`.

**Comment by Scuilion** [comment]
I must be misunderstanding something. The CommitDiff object has a rename instance variable, so how would I go about finding the files that have change names in a commit?

**Comment by ajoberstar** [comment]
Oh, I was confusing this with status. I'll have to look at this in more detail to see what's wrong.

**Comment by Scuilion** [comment]
Thanks!!

**Comment by ajoberstar** [comment]
Turns out, rename detection is a separate API in JGit. I never had a test for renames so I didn't catch it. Working on a fix right now, and will have it out as 1.4.0-rc.2 pretty quick.

**Comment by ajoberstar** [comment]
FYI, just validated this on your test repo. Assuming it's just the one commit with a rename, this should be good to go. I'm going to push out 1.4.0 final now.

**Comment by Scuilion** [comment]
Dude, you're the man!
