### ISSUE TITLE
Add a progress bar

### ISSUE THREAD

**Issue by GabrielTK** [ajoberstar/grgit#75]
Hi!
I want to use this in my installer in groovy, but i need a way to Interact with progress bar. can you help me please?

**Comment by ajoberstar** [comment]
Right now, there aren't any progress APIs exposed. You'd have to use JGit directly of you have an immediate need for this. I'll add it to the wishlist though.

**Comment by ajoberstar** [comment]
I still plan to add this to the wishlist so I'll leave it open.
