### ISSUE TITLE
LogOp: Support for --first-parent and --no-merges

### ISSUE THREAD

**Issue by nikolauskrismer** [ajoberstar/grgit#77]
Hi,

first I have to write a big "THANK YOU" for this plugin.
It helps me a lot dealing with git in gradle.

However, there is one thing that's missing that I would need.
Is it possible to get a result from LogOp that's identical to "git log myTag --first-parent --no-merges"?

By now I get all commit messages, but in fact I only want those from the master branch without merge commit messages. The "--first-parent --no-merges" options are also explained here (that's why I found them):
http://stackoverflow.com/questions/10248137/git-how-to-list-commits-on-this-branch-but-not-from-merged-branches

**Comment by ajoberstar** [comment]
I don't think JGit has direct support for those options (see [LogCommand](http://download.eclipse.org/jgit/site/3.7.0.201502260915-r/apidocs/org/eclipse/jgit/api/LogCommand.html)). Since I try to stick to JGit's porcelain commands, I'd suggest filing an issue with JGit to see if that could be enhanced.

**Comment by nikolauskrismer** [comment]
Ok... I understand. Thanks for the support so far.

I filled a bug for jgit (Bug 476697 here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=476697).
Let's see if they are willing to extend LogCommand.
If so, it would be great to have these options in grgit also (and if not you can close this bug :-)

**Comment by ajoberstar** [comment]
Yeah, if they patch it let me know and this can be enhanced.

**Comment by ajoberstar** [comment]
Confirming that the JGit bug is still open as of 10/22/2017.

**Comment by mmichaelis** [comment]
As workaround for `--no-merges` you could use the following approach:

```groovy
grgit.log(maxCommits: 10).find { it.parentIds.size() == 1 }
```

which is nearly the same as `--no-merges`. Unfortunately, as filtering happens after the log command has been executed, it is more likely that the result of `find` is `null` (I emphasized this in the example by using `maxCommits = 10` as we may end up with 10 log entries in a row, which are all merge commits...).

While it seems to be unlikely that JGit will support `--no-merges` directly, it may be possible to use the option `RevFilter` in [LogCommand][]. As can be seen in JavaDoc of [RevFilter][], we then have the option to filter for example by `no-merges` as well as `only-merges`.

[LogCommand]: <https://download.eclipse.org/jgit/site/5.2.1.201812262042-r/apidocs/index.html> "LogCommand (JGit - Parent 5.2.1.201812262042-r API)"
[RevFilter]: <https://download.eclipse.org/jgit/site/5.2.1.201812262042-r/apidocs/org/eclipse/jgit/revwalk/filter/RevFilter.html> "RevFilter (JGit - Parent 5.2.1.201812262042-r API)"

**Comment by ajoberstar** [comment]
As is now noted in the [readme](https://github.com/ajoberstar/grgit?tab=readme-ov-file#project-status) this plugin is feature frozen. No new features will be added.
