### ISSUE TITLE
Possible to rename tags?

### ISSUE THREAD

**Issue by bedge** [ajoberstar/grgit#79]
Does this API provide a way to rename tags?
Or, create tags with a new name using an existing Tag instance?

I'm automating our release branch creation and when I create the new release branch, I want to rename all of the CI generated develop tags to use use the release branch name.

IOW, rename  jenkins-App-build-develop-180 ->  jenkins-App-build-release_xxx-180

so then then jenkins can start form number 1 again on the develop builds & tags.

I could just blow them away, but I like the idea of preserving then under the new branch.

**Comment by ajoberstar** [comment]
There aren't any tag rename (or delete) options in Grgit, though I'm not sure CLI Git supports renames either.

You can easily create a new tag pointing to the same commit though. See [TagAddOp#pointsTo](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/TagAddOp.html). An instance of `Tag` is a valid value for `pointsTo`.

**Comment by bedge** [comment]
Got it working:
```
task reanmeDevelopTags() {
	group = "Release"
	description = "Rename develop tags into release tags"
	doLast {
		def release = System.getProperty("release.name")
		if (null == release) {
			throw new GradleException("-Drelease.name=.. missing.")
		}
		def developToken = "build-develop"
		def releaseReplacement = "build-release_${release}"
		def repo = Grgit.open(project.file('.'))
		def tags = repo.tag.list()
		tags.forEach() { tag ->
			String tagName = tag.getFullName()
			if(tagName.contains(developToken)) {
					String tagNewName = tagName.replace(developToken, releaseReplacement)
					println "Rename tag ${tagName} -> ${tagNewName}"
					Tag newTag = repo.tag.add(name: tagNewName, pointsTo: tag)
					repo.tag.remove(names: [tagName])
			}
		}
	}
}
```
