### ISSUE TITLE
UnknownHostKey

### ISSUE THREAD

**Issue by poping888** [ajoberstar/grgit#82]
Error:(51, 0) UnknownHostKey: 192.168.0.238. RSA key fingerprint is 3a:9f:1b:27:bb:a2:cd:e6:8d:78:e1:18:a3:ef:4b:16
why?

**Comment by ajoberstar** [comment]
I'll need more information about what you're doing when you see this error.

**Comment by poping888** [comment]
thinks,fixed
1. C:\Users\user\.ssh\config (if not,create)
2.
Host 192.168.11.194
StrictHostKeyChecking no
UserKnownHostsFile=/dev/null
3.save,run project

**Comment by ajoberstar** [comment]
Sorry, I'm still not sure I'm following, but this [StackOverflow thread discusses UnknownHostKey errors from JGit](http://stackoverflow.com/questions/2003419/com-jcraft-jsch-jschexception-unknownhostkey). Is there a reason you aren't checking host keys? Whether there's anything to do in grgit to support this depends on the use case for this.

**Comment by estani** [comment]
Well I might have the same issue. The Problem ist that apparently in windows the default file %USERPROFILE%\.ssh\known_hosts is not being used by Grgit at all. 
I have called git clone to make sure the fingerprint gets loaded in that file and that I have the fingerprint for both the host name and ip (just in case). 
Git doesn't complaint anymore, Grgit "unknow host" popup keeps on appearing.

**Comment by ajoberstar** [comment]
That's odd. I use Windows a good chunk of the time and it has picked up the known_hosts somehow. Maybe there's some other source it's using that I'm not aware of.

**Comment by ajoberstar** [comment]
#95 would be a workaround to this. Doesn't seem like the best solution for these particular instances though.

**Comment by ajoberstar** [comment]
I might reopen this if I end up seeing this behavior some more, but it hasn't seemed to happen to me recently. And there's now (when 1.7.0 comes out) a workaround: see #109.

**Comment by vitalii-vitrenko** [comment]
Have the same issue on with grgit 2.0.0 on Windows

**Comment by codeNoobie** [comment]
I am getting this error. How exactly do we fix this?

**Comment by ajoberstar** [comment]
@codeNoobie what version are you using?
