### ISSUE TITLE
Is thre a way to skip the checkSnapshotDependencies  check?

### ISSUE THREAD

**Issue by bedge** [ajoberstar/grgit#87]
I know this is a "bad idea", but I have a project that has a local dependency that is by definition -SNAPSHOT until it's released.
Sort of a chicken/egg problem.

If I can disable this check, after the release it won't be a snapshot dependency anymore.

**Comment by bedge** [comment]
Just found gradle's -x switch, ie: `gradle -x checkSnapshotDependencies`, which addresses this problem.

**Comment by kopax** [comment]
What is the `checkSnapshotDependencies` exactly for ?

**Comment by ajoberstar** [comment]
This repo does not include any Gradle plugin and none of my plugins provide that task. I'm guessing it was mistakenly opened here.
