### ISSUE TITLE
Cannot remove all files from repository

### ISSUE THREAD

**Issue by lucacorti** [ajoberstar/grgit#88]
Hello,

I am able to add all the files in the repo directory with:

```
repo.add(patterns: ['.'])
```

But deleting files from the respository with

```
repo.remove(patterns: ['.'])
```

Fails silently. Is there a way to remove all files from a Grgit.repo object?

**Comment by ajoberstar** [comment]
I don't think `remove` will work with anything besides specific paths. I believe this is a JGit limitation, see [mention in doc](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/RmOp.html) and [test](https://github.com/ajoberstar/grgit/blob/master/src/test/groovy/org/ajoberstar/grgit/operation/RmOpSpec.groovy#L52).

You might be best off deleting all of the files using normal Java/Groovy APIs and then you should be able to use:

```
grgit.add(cached: true)
```

**Comment by lucacorti** [comment]
That didn't work for me, I ended up solving it in a slightly different way:

```
        def repo = Grgit.clone(dir: outDir, uri: repoURL)
        FileTree tree = fileTree (dir: outDir);
        tree.exclude ".git"
        tree.each { File file ->
            String relativePath = new File(outDir).toURI().relativize(file.toURI()).getPath().toString()
            repo.remove(patterns: [relativePath])
        }
```

**Comment by ajoberstar** [comment]
Sure, that makes sense. Thanks for the follow-up.
