### ISSUE TITLE
Status not accessible

### ISSUE THREAD

**Issue by MFornander** [ajoberstar/grgit#89]
Apologies if I'm using your plugin incorrectly.  I simply want to use Status.isClean() to see if I need to append a flag to my builds indicating dirty.  I'm using raw GrGit and not git-gradle.  Is this possible, and if not can we expose the creation of a Status instance to the public?

**Comment by ajoberstar** [comment]
Yes, this is possibly. Looks like I'm missing a link from the main Grgit doc, but the usage is shown on [StatusOp](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/StatusOp.html).

**Comment by MFornander** [comment]
Thank you! Worked perfectly:
def gitClean = grGit.status().isClean() ? "" : "-DIRTY"
