### ISSUE TITLE
Remove println from PullOp

### ISSUE THREAD

**Issue by jthurne** [ajoberstar/grgit#91]
[Line 97 of PullOp] (https://github.com/ajoberstar/grgit/blob/v1.4.1/src/main/groovy/org/ajoberstar/grgit/operation/PullOp.groovy#L97) has an unhelpful println.  The JGit PullResult class does override toString, but its members (FetchResult, MergeResult, and RebaseResult) do not. When PullOp is executed, something similar to:

    org.eclipse.jgit.transport.FetchResult@db188ae6
    org.eclipse.jgit.api.RebaseResult@e7b8848a

...is printed to standard out. This is rather annoying when you are trying to use Grgit in a console-based application.

To fix the issue, please delete the println.

**Comment by ajoberstar** [comment]
Agreed. I'll put this in the next release.
