### ISSUE TITLE
Merge commit contains incorrect message

### ISSUE THREAD

**Issue by Blacktiger** [ajoberstar/grgit#93]
I created some code to do a simple merge. After the merge the commit message is `Merge commit '08d91d8f29daf525a6cd6e0fe39c360d3775561c' into develop` rather than the expected `Merge branch 'origin/master'`.

Example Code:
```
repository.checkout(branch: 'develop')
repository.merge(head: 'origin/master', mode: MergeOp.Mode.CREATE_COMMIT)
```

**Comment by ajoberstar** [comment]
Off the top of my head, I would guess this has to do with the approach of collapsing all inputs to `head` down to a commit ID. It should probably attempt to get a ref name first.

A pull request would be welcome, otherwise I might look into this myself for the next release.

**Comment by Blacktiger** [comment]
I opened a pull request after playing around with jgit for a bit. I'm unfamiliar with jgit or spock though so please look it over. The existing tests were not broken, but I would need a bit more time to add additional tests for the new functionality.
